import { AnimatePresence, motion } from 'framer-motion'
import { AlertTriangle, BriefcaseBusiness, Check, CheckCheck, CloudRain, LocateFixed, PackageCheck, ShoppingBag, Sparkles, X } from 'lucide-react'
import { useState } from 'react'
import { ItemIcon } from '../components/item-icon'
import { PageHeader, PrimaryButton } from '../components/ui'
import { useHomeStore } from '../store/use-home-store'
import type { ChecklistItem } from '../types'

export function ChecklistPage() {
  const checklist = useHomeStore((state) => state.checklist)
  const toggle = useHomeStore((state) => state.toggleChecklist)
  const setAll = useHomeStore((state) => state.setAllChecklist)
  const [detail, setDetail] = useState<ChecklistItem | null>(null)
  const [smartResult, setSmartResult] = useState(false)
  const [shopping, setShopping] = useState(false)
  const done = checklist.filter((item) => item.checked).length
  const missing = checklist.filter((item) => !item.checked)
  const allDone = done === checklist.length

  return <div className="page-container">
    <PageHeader eyebrow="出门模式 · 商务会议" title="出门前，再安心确认一次。" description="系统会结合雷阵雨天气与今晚的商务行程，检查容易遗漏的重要物品。" />
    <section className="content-section pt-0"><div className="grid gap-3 md:grid-cols-3"><StatusCard className="blue" icon={<CloudRain/>} label="天气" value="雷阵雨 · 27°C" note="降雨概率 82%"/><StatusCard className="purple" icon={<BriefcaseBusiness/>} label="行程" value="商务会议" note="19:30 · 科创中心"/><StatusCard className="teal" icon={<PackageCheck/>} label="准备进度" value={`${done} / ${checklist.length}`} note={`${Math.round(done / checklist.length * 100)}% 已完成`} progress={done/checklist.length*100}/></div></section>
    <section className="content-section"><div className="mb-7 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><h2 className="section-heading">随身物品</h2><p className="mt-2 text-sm text-white/40">必备项优先显示，位置记录随时可查</p></div><div className="flex flex-wrap gap-2"><button className="secondary-button" onClick={() => setAll(true)}><CheckCheck size={16}/>全选</button><button className="secondary-button" onClick={() => setAll(false)}>清空</button><PrimaryButton onClick={() => setSmartResult(true)}><Sparkles size={17}/>智能检查</PrimaryButton></div></div>
      <div className="space-y-2">{checklist.map((item, index) => <motion.div key={item.id} initial={{ opacity: 0, x: -15 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .035 }} className={`checklist-row ${item.checked ? 'checked' : ''}`}><button onClick={() => toggle(item.id)} className={`check-control ${item.checked ? 'active' : ''}`} aria-label={`切换${item.name}`}>{item.checked && <motion.span initial={{ scale: 0, rotate: -30 }} animate={{ scale: 1, rotate: 0 }}><Check size={15}/></motion.span>}</button><span className="item-icon-small"><ItemIcon name={item.icon} size={21}/></span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h3 className="font-medium">{item.name}</h3><span className="category-tag">{item.category}</span>{item.essential && <span className="essential-tag">必备</span>}</div><p className="mt-1 truncate text-xs text-white/35">{item.location}</p></div><button className="location-button" onClick={() => setDetail(item)}><LocateFixed size={15}/><span className="hidden sm:inline">查看位置详情</span></button></motion.div>)}</div>
      <div className="mt-6 flex justify-end"><button className="secondary-button" onClick={() => setShopping(true)}><ShoppingBag size={17}/>生成购物清单</button></div>
    </section>
    <AnimatePresence>{smartResult && <section className="content-section"><motion.div className="result-panel" initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }}><div className="flex items-start justify-between"><div><p className="eyebrow">智能检查完成</p><h2 className="section-heading">{allDone ? '全部准备完成，可以出发。' : `还有 ${missing.length} 件物品未确认。`}</h2></div><button className="icon-button" onClick={() => setSmartResult(false)}><X size={18}/></button></div>{allDone ? <motion.div className="celebration" animate={{ scale: [1, 1.04, 1] }} transition={{ repeat: Infinity, duration: 2 }}><CheckCheck size={40}/><span>准备周全，祝你一路顺利</span></motion.div> : <div className="mt-7 grid gap-3 md:grid-cols-2"><Insight title="天气推荐" items={['雨伞', '口罩']} checklist={checklist}/><Insight title="行程推荐" items={['笔记本电脑', '充电宝']} checklist={checklist}/><div className="rounded-2xl border border-red-400/15 bg-red-400/[.05] p-5 md:col-span-2"><div className="flex items-center gap-2 text-sm text-red-200"><AlertTriangle size={17}/>重要提醒</div><p className="mt-3 text-sm text-white/45">{missing.filter((item) => item.essential).map((item) => item.name).join('、') || '必备物品已全部确认'}{missing.some((item) => item.essential) && '尚未携带。'}</p></div></div>}</motion.div></section>}</AnimatePresence>
    <AnimatePresence>{detail && <motion.div className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setDetail(null)}><motion.div className="modal-card location-modal" initial={{ scale: .88, y: 35 }} animate={{ scale: 1, y: 0 }} exit={{ scale: .9 }} onClick={(event) => event.stopPropagation()}><button className="icon-button absolute right-5 top-5" onClick={() => setDetail(null)}><X size={18}/></button><div className="location-visual"><ItemIcon name={detail.icon} size={72}/></div><p className="eyebrow mt-7">{detail.category} · 位置记录</p><h2 className="mt-2 text-3xl font-medium">{detail.name}</h2><p className="mt-5 text-sm leading-7 text-white/55">{detail.detail}</p><div className="mt-6 flex items-center gap-3 rounded-xl bg-white/5 p-4 text-sm"><LocateFixed size={18} className="text-teal-300"/><span>{detail.location}</span></div></motion.div></motion.div>}</AnimatePresence>
    <AnimatePresence>{shopping && <motion.div className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setShopping(false)}><motion.div className="modal-card" initial={{ scale: .9 }} animate={{ scale: 1 }} onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between"><div><p className="eyebrow">待补齐物品</p><h2 className="mt-2 text-2xl font-medium">购物清单 · {missing.length} 项</h2></div><button className="icon-button" onClick={() => setShopping(false)}><X size={18}/></button></div><div className="mt-6 max-h-72 space-y-2 overflow-auto">{missing.map((item) => <div className="plan-row" key={item.id}><ItemIcon name={item.icon} size={19}/><strong>{item.name}</strong>{item.essential && <span className="ml-auto status-label urgent">紧急</span>}</div>)}</div><div className="mt-5 rounded-xl bg-teal-300/[.08] p-4 text-sm text-teal-100/60">必备 {missing.filter((item) => item.essential).length} 项 · 普通 {missing.filter((item) => !item.essential).length} 项</div></motion.div></motion.div>}</AnimatePresence>
  </div>
}

function StatusCard({ className, icon, label, value, note, progress }: { className: string; icon: React.ReactNode; label: string; value: string; note: string; progress?: number }) { return <article className={`status-card ${className}`}><div className="flex items-center justify-between"><span className="status-card-icon">{icon}</span><span className="text-xs opacity-55">{label}</span></div><h3 className="mt-8 text-xl font-medium">{value}</h3><p className="mt-1 text-xs opacity-55">{note}</p>{progress !== undefined && <div className="mt-4 h-1 rounded-full bg-white/10"><motion.div className="h-full rounded-full bg-teal-300" initial={{ width: 0 }} animate={{ width: `${progress}%` }}/></div>}</article> }
function Insight({ title, items, checklist }: { title: string; items: string[]; checklist: ChecklistItem[] }) { return <div className="rounded-2xl bg-white/[.04] p-5"><h3 className="text-sm text-white/45">{title}</h3><div className="mt-4 space-y-2">{items.map((name) => { const item = checklist.find((entry) => entry.name === name); return <div className="flex items-center gap-2 text-sm" key={name}><span className={`size-2 rounded-full ${item?.checked ? 'bg-teal-300' : 'bg-amber-300'}`}/>{name}<span className="ml-auto text-xs text-white/30">{item?.checked ? '已准备' : '建议携带'}</span></div>})}</div></div> }
