from database import SessionLocal, City, House, Review, Guide
from sqlalchemy import func
import random

cities_data = [
    {"name": "六盘水", "province": "贵州", "lat": 26.59, "lng": 104.83, "altitude": 1800, "summer_temp": "22℃", "winter_temp": "5℃", "air_quality": "优", "humidity": "65%", "rent_avg": 1500, "rent_desc": "800-1500/月", "medical_score": 4.0, "transport_score": 4.0, "living_score": 4.5, "elderly_score": 92, "category": "避暑", "tags": "中国凉都,高海拔,夏季避暑", "description": "六盘水被誉为'中国凉都'，夏季平均气温仅22℃，是夏季避暑旅居的首选目的地。", "hospitals_3a": 3, "has_high_speed_rail": 1, "airport_distance": 20, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "昆明", "province": "云南", "lat": 25.04, "lng": 102.68, "altitude": 1890, "summer_temp": "23℃", "winter_temp": "10℃", "air_quality": "优", "humidity": "60%", "rent_avg": 2200, "rent_desc": "1500-3000/月", "medical_score": 4.8, "transport_score": 4.8, "living_score": 4.8, "elderly_score": 90, "category": "避暑", "tags": "四季如春,省会,交通便利", "description": "昆明四季如春，医疗、交通、生活配套完善，是退休旅居的热门城市。", "hospitals_3a": 15, "has_high_speed_rail": 1, "airport_distance": 25, "image_url": "https://images.unsplash.com/photo-1598896528569-af5c1dc7e40f?w=800"},
    {"name": "贵阳", "province": "贵州", "lat": 26.65, "lng": 106.63, "altitude": 1100, "summer_temp": "24℃", "winter_temp": "6℃", "air_quality": "良", "humidity": "70%", "rent_avg": 1800, "rent_desc": "1200-2500/月", "medical_score": 4.5, "transport_score": 5.0, "living_score": 4.5, "elderly_score": 88, "category": "避暑", "tags": "省会,交通枢纽,夏季凉爽", "description": "贵阳是西南交通枢纽，夏季凉爽，医疗资源丰富，生活便利。", "hospitals_3a": 12, "has_high_speed_rail": 1, "airport_distance": 15, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "西昌", "province": "四川", "lat": 27.89, "lng": 102.26, "altitude": 1500, "summer_temp": "25℃", "winter_temp": "12℃", "air_quality": "优", "humidity": "55%", "rent_avg": 1200, "rent_desc": "800-1800/月", "medical_score": 3.5, "transport_score": 3.5, "living_score": 4.0, "elderly_score": 85, "category": "避暑", "tags": "阳光充足,邛海,冬季温暖", "description": "西昌阳光充足，邛海湿地公园环境优美，适合长期旅居。", "hospitals_3a": 2, "has_high_speed_rail": 0, "airport_distance": 15, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "长白山", "province": "吉林", "lat": 42.32, "lng": 128.12, "altitude": 1000, "summer_temp": "20℃", "winter_temp": "-15℃", "air_quality": "优", "humidity": "60%", "rent_avg": 1500, "rent_desc": "1000-2000/月", "medical_score": 3.0, "transport_score": 2.5, "living_score": 3.0, "elderly_score": 78, "category": "避暑", "tags": "森林气候,自然风光,夏季避暑", "description": "长白山森林覆盖率高，夏季凉爽宜人，空气清新，适合喜欢自然的老人。", "hospitals_3a": 1, "has_high_speed_rail": 0, "airport_distance": 80, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "承德", "province": "河北", "lat": 40.95, "lng": 117.96, "altitude": 350, "summer_temp": "24℃", "winter_temp": "-5℃", "air_quality": "良", "humidity": "55%", "rent_avg": 1500, "rent_desc": "1000-2000/月", "medical_score": 3.5, "transport_score": 4.0, "living_score": 4.0, "elderly_score": 82, "category": "避暑", "tags": "距离北京近,避暑山庄,皇家园林", "description": "承德是清代皇家避暑胜地，距离北京仅2小时车程，夏季凉爽。", "hospitals_3a": 3, "has_high_speed_rail": 1, "airport_distance": 30, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "西双版纳", "province": "云南", "lat": 22.02, "lng": 100.80, "altitude": 550, "summer_temp": "28℃", "winter_temp": "20℃", "air_quality": "优", "humidity": "75%", "rent_avg": 2500, "rent_desc": "2000-3500/月", "medical_score": 3.5, "transport_score": 3.5, "living_score": 4.0, "elderly_score": 85, "category": "避寒", "tags": "热带雨林,温暖过冬,民族文化", "description": "西双版纳冬季温暖如春，热带雨林气候，适合避寒过冬。", "hospitals_3a": 2, "has_high_speed_rail": 0, "airport_distance": 5, "image_url": "https://images.unsplash.com/photo-1598896528569-af5c1dc7e40f?w=800"},
    {"name": "陵水", "province": "海南", "lat": 18.51, "lng": 110.04, "altitude": 10, "summer_temp": "30℃", "winter_temp": "22℃", "air_quality": "优", "humidity": "80%", "rent_avg": 3000, "rent_desc": "2000-4500/月", "medical_score": 3.0, "transport_score": 3.0, "living_score": 3.5, "elderly_score": 80, "category": "避寒", "tags": "海边养老,冬季温暖,清水湾", "description": "陵水位于海南岛东南部，冬季温暖舒适，海水清澈，沙滩优美。", "hospitals_3a": 1, "has_high_speed_rail": 1, "airport_distance": 70, "image_url": "https://images.unsplash.com/photo-1598896528569-af5c1dc7e40f?w=800"},
    {"name": "北海", "province": "广西", "lat": 21.48, "lng": 109.12, "altitude": 10, "summer_temp": "29℃", "winter_temp": "16℃", "air_quality": "良", "humidity": "78%", "rent_avg": 1500, "rent_desc": "1000-2500/月", "medical_score": 3.5, "transport_score": 3.5, "living_score": 4.0, "elderly_score": 83, "category": "避寒", "tags": "海边养老,低成本,银滩", "description": "北海是中国著名的海边养老城市，生活成本低，冬季温暖。", "hospitals_3a": 2, "has_high_speed_rail": 1, "airport_distance": 25, "image_url": "https://images.unsplash.com/photo-1598896528569-af5c1dc7e40f?w=800"},
    {"name": "珠海", "province": "广东", "lat": 22.27, "lng": 113.57, "altitude": 20, "summer_temp": "28℃", "winter_temp": "16℃", "air_quality": "优", "humidity": "75%", "rent_avg": 3000, "rent_desc": "2500-5000/月", "medical_score": 4.5, "transport_score": 4.5, "living_score": 4.8, "elderly_score": 88, "category": "避寒", "tags": "医疗交通好,宜居城市,海边", "description": "珠海环境优美，医疗和交通配套完善，连续多年被评为中国最宜居城市之一。", "hospitals_3a": 8, "has_high_speed_rail": 1, "airport_distance": 40, "image_url": "https://images.unsplash.com/photo-1598896528569-af5c1dc7e40f?w=800"},
    {"name": "厦门", "province": "福建", "lat": 24.49, "lng": 118.09, "altitude": 20, "summer_temp": "27℃", "winter_temp": "14℃", "air_quality": "优", "humidity": "72%", "rent_avg": 3500, "rent_desc": "2500-5000/月", "medical_score": 4.5, "transport_score": 4.5, "living_score": 4.5, "elderly_score": 87, "category": "避寒", "tags": "生活方便,海岛,环境优美", "description": "厦门气候宜人，生活便利，医疗资源丰富，是高品质养老城市。", "hospitals_3a": 8, "has_high_speed_rail": 1, "airport_distance": 15, "image_url": "https://images.unsplash.com/photo-1598896528569-af5c1dc7e40f?w=800"},
    {"name": "大理", "province": "云南", "lat": 25.59, "lng": 100.23, "altitude": 1970, "summer_temp": "23℃", "winter_temp": "9℃", "air_quality": "优", "humidity": "60%", "rent_avg": 1800, "rent_desc": "1200-3000/月", "medical_score": 3.5, "transport_score": 3.5, "living_score": 4.0, "elderly_score": 86, "category": "避暑", "tags": "洱海,古城,文艺养老", "description": "大理洱海风光旖旎，气候温和，是文艺养老的热门目的地。", "hospitals_3a": 2, "has_high_speed_rail": 1, "airport_distance": 15, "image_url": "https://images.unsplash.com/photo-1598896528569-af5c1dc7e40f?w=800"},
    {"name": "丽江", "province": "云南", "lat": 26.87, "lng": 100.23, "altitude": 2400, "summer_temp": "22℃", "winter_temp": "8℃", "air_quality": "优", "humidity": "55%", "rent_avg": 1500, "rent_desc": "1000-2500/月", "medical_score": 3.0, "transport_score": 3.5, "living_score": 3.5, "elderly_score": 82, "category": "避暑", "tags": "古城,高原,夏季凉爽", "description": "丽江古城是世界文化遗产，夏季凉爽，适合短期旅居。", "hospitals_3a": 1, "has_high_speed_rail": 1, "airport_distance": 30, "image_url": "https://images.unsplash.com/photo-1598896528569-af5c1dc7e40f?w=800"},
    {"name": "三亚", "province": "海南", "lat": 18.25, "lng": 109.51, "altitude": 10, "summer_temp": "30℃", "winter_temp": "23℃", "air_quality": "优", "humidity": "78%", "rent_avg": 4000, "rent_desc": "3000-8000/月", "medical_score": 4.0, "transport_score": 4.0, "living_score": 4.0, "elderly_score": 82, "category": "避寒", "tags": "热带海滨,过冬首选,医疗完善", "description": "三亚是中国最著名的避寒胜地，拥有优质的海滨资源和成熟的医疗配套。", "hospitals_3a": 5, "has_high_speed_rail": 1, "airport_distance": 15, "image_url": "https://images.unsplash.com/photo-1598896528569-af5c1dc7e40f?w=800"},
    {"name": "成都", "province": "四川", "lat": 30.57, "lng": 104.07, "altitude": 500, "summer_temp": "27℃", "winter_temp": "7℃", "air_quality": "良", "humidity": "75%", "rent_avg": 2500, "rent_desc": "2000-4000/月", "medical_score": 5.0, "transport_score": 5.0, "living_score": 5.0, "elderly_score": 90, "category": "避暑", "tags": "美食,医疗顶级,生活安逸", "description": "成都以美食和慢生活闻名，医疗资源在全国名列前茅。", "hospitals_3a": 30, "has_high_speed_rail": 1, "airport_distance": 20, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "大连", "province": "辽宁", "lat": 38.91, "lng": 121.62, "altitude": 30, "summer_temp": "24℃", "winter_temp": "-2℃", "air_quality": "良", "humidity": "65%", "rent_avg": 2000, "rent_desc": "1500-3000/月", "medical_score": 4.5, "transport_score": 4.5, "living_score": 4.5, "elderly_score": 86, "category": "避暑", "tags": "海滨城市,医疗好,环境优美", "description": "大连是东北最宜居的海滨城市，夏季凉爽，医疗资源丰富。", "hospitals_3a": 12, "has_high_speed_rail": 1, "airport_distance": 15, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "青岛", "province": "山东", "lat": 36.07, "lng": 120.38, "altitude": 20, "summer_temp": "25℃", "winter_temp": "1℃", "air_quality": "良", "humidity": "70%", "rent_avg": 2500, "rent_desc": "2000-4000/月", "medical_score": 4.5, "transport_score": 4.5, "living_score": 4.5, "elderly_score": 87, "category": "避暑", "tags": "海滨,啤酒,医疗完善", "description": "青岛红瓦绿树碧海蓝天，夏季气候宜人，是北方最佳避暑城市之一。", "hospitals_3a": 12, "has_high_speed_rail": 1, "airport_distance": 30, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "烟台", "province": "山东", "lat": 37.46, "lng": 121.45, "altitude": 20, "summer_temp": "25℃", "winter_temp": "-1℃", "air_quality": "优", "humidity": "65%", "rent_avg": 1500, "rent_desc": "1000-2500/月", "medical_score": 4.0, "transport_score": 4.0, "living_score": 4.0, "elderly_score": 84, "category": "避暑", "tags": "海滨,长寿之乡,房价低", "description": "烟台是中国长寿之乡，环境优美，生活成本低，适合长期养老。", "hospitals_3a": 5, "has_high_speed_rail": 1, "airport_distance": 15, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "威海", "province": "山东", "lat": 37.51, "lng": 122.12, "altitude": 20, "summer_temp": "24℃", "winter_temp": "0℃", "air_quality": "优", "humidity": "65%", "rent_avg": 1500, "rent_desc": "1000-2500/月", "medical_score": 3.5, "transport_score": 3.5, "living_score": 4.0, "elderly_score": 85, "category": "避暑", "tags": "最干净城市,海滨,养老", "description": "威海是中国最干净的城市之一，环境宜人，适合养老。", "hospitals_3a": 4, "has_high_speed_rail": 1, "airport_distance": 40, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "杭州", "province": "浙江", "lat": 30.27, "lng": 120.15, "altitude": 20, "summer_temp": "28℃", "winter_temp": "5℃", "air_quality": "良", "humidity": "72%", "rent_avg": 3500, "rent_desc": "3000-6000/月", "medical_score": 5.0, "transport_score": 5.0, "living_score": 5.0, "elderly_score": 89, "category": "避暑", "tags": "西湖,医疗顶级,生活品质高", "description": "杭州风景如画，医疗和交通配套顶级，是高品质养老城市。", "hospitals_3a": 25, "has_high_speed_rail": 1, "airport_distance": 30, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "苏州", "province": "江苏", "lat": 31.30, "lng": 120.58, "altitude": 10, "summer_temp": "28℃", "winter_temp": "5℃", "air_quality": "良", "humidity": "72%", "rent_avg": 3000, "rent_desc": "2500-5000/月", "medical_score": 4.8, "transport_score": 4.8, "living_score": 4.8, "elderly_score": 88, "category": "避暑", "tags": "园林,水乡,医疗好", "description": "苏州古典园林闻名世界，生活便利，是长三角重要的养老城市。", "hospitals_3a": 15, "has_high_speed_rail": 1, "airport_distance": 50, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "扬州", "province": "江苏", "lat": 32.39, "lng": 119.41, "altitude": 10, "summer_temp": "27℃", "winter_temp": "4℃", "air_quality": "良", "humidity": "70%", "rent_avg": 2000, "rent_desc": "1500-3000/月", "medical_score": 4.0, "transport_score": 4.0, "living_score": 4.5, "elderly_score": 86, "category": "避暑", "tags": "慢生活,美食,园林", "description": "扬州是一座慢节奏的城市，生活安逸，适合养老。", "hospitals_3a": 5, "has_high_speed_rail": 1, "airport_distance": 40, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "无锡", "province": "江苏", "lat": 31.49, "lng": 120.31, "altitude": 10, "summer_temp": "28℃", "winter_temp": "5℃", "air_quality": "良", "humidity": "70%", "rent_avg": 2500, "rent_desc": "2000-4000/月", "medical_score": 4.5, "transport_score": 4.5, "living_score": 4.5, "elderly_score": 87, "category": "避暑", "tags": "太湖,宜居,养老", "description": "无锡太湖风光优美，经济发达，生活配套完善。", "hospitals_3a": 10, "has_high_speed_rail": 1, "airport_distance": 20, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "宁波", "province": "浙江", "lat": 29.87, "lng": 121.54, "altitude": 10, "summer_temp": "28℃", "winter_temp": "6℃", "air_quality": "良", "humidity": "70%", "rent_avg": 2800, "rent_desc": "2000-4500/月", "medical_score": 4.5, "transport_score": 4.5, "living_score": 4.5, "elderly_score": 87, "category": "避暑", "tags": "港口城市,医疗好,生活便利", "description": "宁波经济发达，医疗资源丰富，是宜居养老城市。", "hospitals_3a": 10, "has_high_speed_rail": 1, "airport_distance": 15, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "贵阳", "province": "贵州", "lat": 26.65, "lng": 106.63, "altitude": 1100, "summer_temp": "24℃", "winter_temp": "6℃", "air_quality": "良", "humidity": "70%", "rent_avg": 1800, "rent_desc": "1200-2500/月", "medical_score": 4.5, "transport_score": 5.0, "living_score": 4.5, "elderly_score": 88, "category": "避暑", "tags": "省会,交通枢纽,夏季凉爽", "description": "贵阳是西南交通枢纽，夏季凉爽，医疗资源丰富。", "hospitals_3a": 12, "has_high_speed_rail": 1, "airport_distance": 15, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "南宁", "province": "广西", "lat": 22.82, "lng": 108.37, "altitude": 80, "summer_temp": "28℃", "winter_temp": "14℃", "air_quality": "良", "humidity": "75%", "rent_avg": 1800, "rent_desc": "1200-3000/月", "medical_score": 4.0, "transport_score": 4.5, "living_score": 4.0, "elderly_score": 83, "category": "避寒", "tags": "绿城,省会,冬季温暖", "description": "南宁是中国绿城，冬季温暖，生活成本适中。", "hospitals_3a": 10, "has_high_speed_rail": 1, "airport_distance": 30, "image_url": "https://images.unsplash.com/photo-1598896528569-af5c1dc7e40f?w=800"},
    {"name": "桂林", "province": "广西", "lat": 25.27, "lng": 110.29, "altitude": 150, "summer_temp": "27℃", "winter_temp": "10℃", "air_quality": "优", "humidity": "72%", "rent_avg": 1200, "rent_desc": "800-2000/月", "medical_score": 3.0, "transport_score": 3.5, "living_score": 3.5, "elderly_score": 80, "category": "避暑", "tags": "山水甲天下,低房价,自然风光", "description": "桂林山水甲天下，环境优美，生活成本低。", "hospitals_3a": 3, "has_high_speed_rail": 1, "airport_distance": 30, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "惠州", "province": "广东", "lat": 23.11, "lng": 114.42, "altitude": 20, "summer_temp": "28℃", "winter_temp": "15℃", "air_quality": "优", "humidity": "72%", "rent_avg": 2000, "rent_desc": "1500-3500/月", "medical_score": 3.5, "transport_score": 4.0, "living_score": 4.0, "elderly_score": 84, "category": "避寒", "tags": "西湖,温泉,宜居", "description": "惠州有西湖和丰富的温泉资源，生活节奏慢，适合养老。", "hospitals_3a": 4, "has_high_speed_rail": 1, "airport_distance": 50, "image_url": "https://images.unsplash.com/photo-1598896528569-af5c1dc7e40f?w=800"},
    {"name": "湛江", "province": "广东", "lat": 21.27, "lng": 110.36, "altitude": 10, "summer_temp": "29℃", "winter_temp": "16℃", "air_quality": "良", "humidity": "78%", "rent_avg": 1500, "rent_desc": "1000-2500/月", "medical_score": 3.5, "transport_score": 3.5, "living_score": 3.5, "elderly_score": 80, "category": "避寒", "tags": "海鲜,海滨,低成本", "description": "湛江拥有丰富的海鲜资源，生活成本低，冬季温暖。", "hospitals_3a": 3, "has_high_speed_rail": 1, "airport_distance": 40, "image_url": "https://images.unsplash.com/photo-1598896528569-af5c1dc7e40f?w=800"},
    {"name": "中山", "province": "广东", "lat": 22.52, "lng": 113.38, "altitude": 10, "summer_temp": "28℃", "winter_temp": "15℃", "air_quality": "良", "humidity": "74%", "rent_avg": 2200, "rent_desc": "1500-3500/月", "medical_score": 4.0, "transport_score": 4.0, "living_score": 4.5, "elderly_score": 85, "category": "避寒", "tags": "孙中山故里,宜居,环境好", "description": "中山环境优美，生活便利，是珠三角重要的宜居城市。", "hospitals_3a": 5, "has_high_speed_rail": 1, "airport_distance": 60, "image_url": "https://images.unsplash.com/photo-1598896528569-af5c1dc7e40f?w=800"},
    {"name": "佛山", "province": "广东", "lat": 23.02, "lng": 113.12, "altitude": 10, "summer_temp": "28℃", "winter_temp": "15℃", "air_quality": "良", "humidity": "74%", "rent_avg": 2000, "rent_desc": "1500-3500/月", "medical_score": 4.0, "transport_score": 4.5, "living_score": 4.5, "elderly_score": 85, "category": "避寒", "tags": "武术之乡,美食,宜居", "description": "佛山是岭南文化名城，生活便利，美食丰富。", "hospitals_3a": 8, "has_high_speed_rail": 1, "airport_distance": 50, "image_url": "https://images.unsplash.com/photo-1598896528569-af5c1dc7e40f?w=800"},
    {"name": "柳州", "province": "广西", "lat": 24.33, "lng": 109.42, "altitude": 100, "summer_temp": "27℃", "winter_temp": "12℃", "air_quality": "良", "humidity": "72%", "rent_avg": 1000, "rent_desc": "800-1800/月", "medical_score": 3.5, "transport_score": 3.5, "living_score": 3.5, "elderly_score": 80, "category": "避暑", "tags": "柳州螺蛳粉,低房价,山水城市", "description": "柳州是山水城市，生活成本极低，适合预算有限的老人。", "hospitals_3a": 4, "has_high_speed_rail": 1, "airport_distance": 20, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "昆明安宁", "province": "云南", "lat": 24.92, "lng": 102.48, "altitude": 1800, "summer_temp": "23℃", "winter_temp": "10℃", "air_quality": "优", "humidity": "60%", "rent_avg": 1200, "rent_desc": "800-1800/月", "medical_score": 3.0, "transport_score": 3.0, "living_score": 3.5, "elderly_score": 84, "category": "避暑", "tags": "温泉,安宁疗养,森林覆盖", "description": "安宁以温泉闻名，森林覆盖率高，是昆明周边的康养胜地。", "hospitals_3a": 1, "has_high_speed_rail": 0, "airport_distance": 60, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "普洱", "province": "云南", "lat": 22.83, "lng": 100.97, "altitude": 1300, "summer_temp": "24℃", "winter_temp": "14℃", "air_quality": "优", "humidity": "68%", "rent_avg": 1200, "rent_desc": "800-2000/月", "medical_score": 2.5, "transport_score": 2.5, "living_score": 3.0, "elderly_score": 78, "category": "避暑", "tags": "普洱茶,森林城市,慢生活", "description": "普洱是世界茶源，空气清新，生活节奏慢，适合康养。", "hospitals_3a": 1, "has_high_speed_rail": 0, "airport_distance": 5, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "腾冲", "province": "云南", "lat": 25.02, "lng": 98.50, "altitude": 1640, "summer_temp": "23℃", "winter_temp": "12℃", "air_quality": "优", "humidity": "65%", "rent_avg": 1500, "rent_desc": "1000-2500/月", "medical_score": 2.5, "transport_score": 2.5, "living_score": 3.0, "elderly_score": 80, "category": "避暑", "tags": "温泉,火山,银杏村", "description": "腾冲以温泉和火山地貌闻名，环境优美，适合康养旅居。", "hospitals_3a": 1, "has_high_speed_rail": 0, "airport_distance": 15, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "玉溪", "province": "云南", "lat": 24.35, "lng": 102.55, "altitude": 1700, "summer_temp": "23℃", "winter_temp": "10℃", "air_quality": "优", "humidity": "62%", "rent_avg": 1200, "rent_desc": "800-2000/月", "medical_score": 3.0, "transport_score": 3.5, "living_score": 3.5, "elderly_score": 82, "category": "避暑", "tags": "抚仙湖,烟草,宜居", "description": "玉溪有抚仙湖优质水资源，气候温和，是云南宜居城市。", "hospitals_3a": 2, "has_high_speed_rail": 1, "airport_distance": 80, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "曲靖", "province": "云南", "lat": 25.50, "lng": 103.80, "altitude": 1850, "summer_temp": "22℃", "winter_temp": "8℃", "air_quality": "优", "humidity": "60%", "rent_avg": 1000, "rent_desc": "800-1500/月", "medical_score": 3.0, "transport_score": 3.5, "living_score": 3.5, "elderly_score": 82, "category": "避暑", "tags": "珠江源,低房价,夏季凉爽", "description": "曲靖是珠江源头，房价低廉，夏季凉爽，适合避暑长住。", "hospitals_3a": 3, "has_high_speed_rail": 1, "airport_distance": 100, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "宜昌", "province": "湖北", "lat": 30.69, "lng": 111.29, "altitude": 60, "summer_temp": "27℃", "winter_temp": "6℃", "air_quality": "良", "humidity": "70%", "rent_avg": 1500, "rent_desc": "1000-2500/月", "medical_score": 4.0, "transport_score": 4.0, "living_score": 4.0, "elderly_score": 83, "category": "避暑", "tags": "三峡,水电之都,宜居", "description": "宜昌是三峡大坝所在地，环境优美，城市宜居。", "hospitals_3a": 5, "has_high_speed_rail": 1, "airport_distance": 30, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "襄阳", "province": "湖北", "lat": 32.01, "lng": 112.12, "altitude": 70, "summer_temp": "27℃", "winter_temp": "5℃", "air_quality": "良", "humidity": "68%", "rent_avg": 1200, "rent_desc": "800-2000/月", "medical_score": 3.5, "transport_score": 4.0, "living_score": 4.0, "elderly_score": 82, "category": "避暑", "tags": "古城,汉江,低房价", "description": "襄阳古城历史悠久，汉江穿城而过，生活成本低。", "hospitals_3a": 4, "has_high_speed_rail": 1, "airport_distance": 20, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "洛阳", "province": "河南", "lat": 34.62, "lng": 112.45, "altitude": 150, "summer_temp": "27℃", "winter_temp": "2℃", "air_quality": "良", "humidity": "60%", "rent_avg": 1200, "rent_desc": "800-2000/月", "medical_score": 4.0, "transport_score": 4.0, "living_score": 4.0, "elderly_score": 84, "category": "避暑", "tags": "古都,牡丹,房价低", "description": "洛阳是十三朝古都，文化底蕴深厚，房价低，适合养老。", "hospitals_3a": 8, "has_high_speed_rail": 1, "airport_distance": 15, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "遵义", "province": "贵州", "lat": 27.70, "lng": 106.93, "altitude": 900, "summer_temp": "25℃", "winter_temp": "6℃", "air_quality": "良", "humidity": "72%", "rent_avg": 1000, "rent_desc": "800-1500/月", "medical_score": 3.0, "transport_score": 3.5, "living_score": 3.5, "elderly_score": 80, "category": "避暑", "tags": "红色旅游,低房价,夏季凉爽", "description": "遵义是红色旅游城市，夏季凉爽，房价低，适合避暑长住。", "hospitals_3a": 4, "has_high_speed_rail": 1, "airport_distance": 40, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "秦皇岛", "province": "河北", "lat": 39.93, "lng": 119.60, "altitude": 20, "summer_temp": "25℃", "winter_temp": "-3℃", "air_quality": "良", "humidity": "62%", "rent_avg": 1800, "rent_desc": "1200-3000/月", "medical_score": 3.5, "transport_score": 4.0, "living_score": 4.0, "elderly_score": 82, "category": "避暑", "tags": "北戴河,海滨,避暑胜地", "description": "秦皇岛北戴河是中国著名的避暑胜地，距北京近。", "hospitals_3a": 4, "has_high_speed_rail": 1, "airport_distance": 15, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "黄山", "province": "安徽", "lat": 29.71, "lng": 118.32, "altitude": 1400, "summer_temp": "22℃", "winter_temp": "2℃", "air_quality": "优", "humidity": "68%", "rent_avg": 1200, "rent_desc": "800-2000/月", "medical_score": 2.5, "transport_score": 3.0, "living_score": 3.0, "elderly_score": 78, "category": "避暑", "tags": "黄山风景区,空气好,夏季凉爽", "description": "黄山风景区夏季凉爽，空气清新，适合喜欢自然风光的老人。", "hospitals_3a": 1, "has_high_speed_rail": 1, "airport_distance": 50, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "井冈山", "province": "江西", "lat": 26.57, "lng": 114.17, "altitude": 800, "summer_temp": "23℃", "winter_temp": "5℃", "air_quality": "优", "humidity": "70%", "rent_avg": 1000, "rent_desc": "800-1500/月", "medical_score": 2.0, "transport_score": 2.5, "living_score": 2.5, "elderly_score": 75, "category": "避暑", "tags": "革命圣地,森林,夏季凉爽", "description": "井冈山森林覆盖率高，夏季凉爽，适合避暑康养。", "hospitals_3a": 1, "has_high_speed_rail": 0, "airport_distance": 80, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "庐山", "province": "江西", "lat": 29.44, "lng": 115.87, "altitude": 1100, "summer_temp": "22℃", "winter_temp": "2℃", "air_quality": "优", "humidity": "72%", "rent_avg": 1200, "rent_desc": "1000-2000/月", "medical_score": 2.0, "transport_score": 2.5, "living_score": 2.5, "elderly_score": 76, "category": "避暑", "tags": "世界遗产,避暑名山,云雾", "description": "庐山是中国四大避暑名山之一，夏季凉爽，风景秀丽。", "hospitals_3a": 1, "has_high_speed_rail": 0, "airport_distance": 60, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "厦门海沧", "province": "福建", "lat": 24.48, "lng": 118.03, "altitude": 10, "summer_temp": "27℃", "winter_temp": "14℃", "air_quality": "优", "humidity": "72%", "rent_avg": 2500, "rent_desc": "1800-3500/月", "medical_score": 3.5, "transport_score": 4.0, "living_score": 4.0, "elderly_score": 84, "category": "避寒", "tags": "海沧湾,环境好,宜居", "description": "海沧是厦门的新兴宜居片区，环境优美，生活配套完善。", "hospitals_3a": 2, "has_high_speed_rail": 0, "airport_distance": 20, "image_url": "https://images.unsplash.com/photo-1598896528569-af5c1dc7e40f?w=800"},
    {"name": "漳州", "province": "福建", "lat": 24.51, "lng": 117.66, "altitude": 20, "summer_temp": "27℃", "winter_temp": "14℃", "air_quality": "优", "humidity": "72%", "rent_avg": 1200, "rent_desc": "800-2000/月", "medical_score": 3.0, "transport_score": 3.5, "living_score": 3.5, "elderly_score": 80, "category": "避寒", "tags": "土楼,水仙花,低房价", "description": "漳州是闽南文化名城，房价低，生活节奏慢。", "hospitals_3a": 3, "has_high_speed_rail": 1, "airport_distance": 60, "image_url": "https://images.unsplash.com/photo-1598896528569-af5c1dc7e40f?w=800"},
    {"name": "泉州", "province": "福建", "lat": 24.91, "lng": 118.58, "altitude": 20, "summer_temp": "27℃", "winter_temp": "14℃", "air_quality": "良", "humidity": "70%", "rent_avg": 2000, "rent_desc": "1500-3000/月", "medical_score": 4.0, "transport_score": 4.0, "living_score": 4.0, "elderly_score": 84, "category": "避寒", "tags": "海上丝绸之路,文化名城,美食", "description": "泉州是海上丝绸之路起点，历史文化悠久，生活便利。", "hospitals_3a": 8, "has_high_speed_rail": 1, "airport_distance": 15, "image_url": "https://images.unsplash.com/photo-1598896528569-af5c1dc7e40f?w=800"},
    {"name": "韶关", "province": "广东", "lat": 24.81, "lng": 113.60, "altitude": 60, "summer_temp": "27℃", "winter_temp": "12℃", "air_quality": "优", "humidity": "70%", "rent_avg": 1000, "rent_desc": "800-1500/月", "medical_score": 3.0, "transport_score": 3.5, "living_score": 3.5, "elderly_score": 80, "category": "避暑", "tags": "丹霞山,低房价,空气好", "description": "韶关有丹霞山世界自然遗产，空气清新，房价低廉。", "hospitals_3a": 3, "has_high_speed_rail": 1, "airport_distance": 35, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "珠海斗门", "province": "广东", "lat": 22.20, "lng": 113.29, "altitude": 10, "summer_temp": "28℃", "winter_temp": "16℃", "air_quality": "优", "humidity": "75%", "rent_avg": 1800, "rent_desc": "1200-2800/月", "medical_score": 3.0, "transport_score": 3.0, "living_score": 3.5, "elderly_score": 80, "category": "避寒", "tags": "田园风光,低成本,温泉", "description": "斗门是珠海的田园片区，生活成本低，有温泉资源。", "hospitals_3a": 1, "has_high_speed_rail": 0, "airport_distance": 50, "image_url": "https://images.unsplash.com/photo-1598896528569-af5c1dc7e40f?w=800"},
    {"name": "柳州", "province": "广西", "lat": 24.33, "lng": 109.42, "altitude": 100, "summer_temp": "27℃", "winter_temp": "12℃", "air_quality": "良", "humidity": "72%", "rent_avg": 1000, "rent_desc": "800-1800/月", "medical_score": 3.5, "transport_score": 3.5, "living_score": 3.5, "elderly_score": 80, "category": "避暑", "tags": "柳州螺蛳粉,低房价,山水城市", "description": "柳州是山水城市，生活成本极低。", "hospitals_3a": 4, "has_high_speed_rail": 1, "airport_distance": 20, "image_url": "https://images.unsplash.com/photo-1587574293340-e0011c4e8ecf?w=800"},
    {"name": "海口", "province": "海南", "lat": 20.04, "lng": 110.34, "altitude": 10, "summer_temp": "30℃", "winter_temp": "20℃", "air_quality": "优", "humidity": "80%", "rent_avg": 2500, "rent_desc": "2000-4000/月", "medical_score": 4.0, "transport_score": 4.0, "living_score": 4.0, "elderly_score": 84, "category": "避寒", "tags": "省会,医疗好,热带", "description": "海口是海南省会，医疗交通配套完善，是避寒过冬的热门城市。", "hospitals_3a": 8, "has_high_speed_rail": 1, "airport_distance": 20, "image_url": "https://images.unsplash.com/photo-1598896528569-af5c1dc7e40f?w=800"},
    {"name": "万宁", "province": "海南", "lat": 18.80, "lng": 110.39, "altitude": 10, "summer_temp": "30℃", "winter_temp": "22℃", "air_quality": "优", "humidity": "80%", "rent_avg": 2500, "rent_desc": "1800-4000/月", "medical_score": 2.5, "transport_score": 3.0, "living_score": 3.0, "elderly_score": 78, "category": "避寒", "tags": "冲浪,海滩,环境优美", "description": "万宁拥有优美的海岸线，冬季温暖，适合喜欢海边生活的老人。", "hospitals_3a": 1, "has_high_speed_rail": 1, "airport_distance": 100, "image_url": "https://images.unsplash.com/photo-1598896528569-af5c1dc7e40f?w=800"},
    {"name": "琼海", "province": "海南", "lat": 19.26, "lng": 110.47, "altitude": 10, "summer_temp": "30℃", "winter_temp": "21℃", "air_quality": "优", "humidity": "80%", "rent_avg": 2000, "rent_desc": "1500-3500/月", "medical_score": 3.0, "transport_score": 3.0, "living_score": 3.5, "elderly_score": 80, "category": "避寒", "tags": "博鳌,田园城市,温泉", "description": "琼海是博鳌亚洲论坛所在地，田园风光优美，有温泉资源。", "hospitals_3a": 2, "has_high_speed_rail": 1, "airport_distance": 100, "image_url": "https://images.unsplash.com/photo-1598896528569-af5c1dc7e40f?w=800"},
]

new_cities = [
    {"name": "宣城", "province": "安徽", "lat": 30.94, "lng": 118.76, "altitude": 50, "summer_temp": "27℃", "winter_temp": "4℃", "air_quality": "优", "humidity": "68%", "rent_avg": 600, "rent_desc": "400-1000/月", "medical_score": 2.5, "transport_score": 3.0, "living_score": 3.5, "elderly_score": 78, "category": "避暑", "tags": "徽文化,低房价,宣纸之乡", "description": "宣城是徽文化发源地之一，房价极低，生活节奏慢，适合预算有限的老人旅居。", "hospitals_3a": 1, "has_high_speed_rail": 1, "airport_distance": 80, "image_url": ""},
    {"name": "池州", "province": "安徽", "lat": 30.66, "lng": 117.49, "altitude": 30, "summer_temp": "27℃", "winter_temp": "4℃", "air_quality": "优", "humidity": "70%", "rent_avg": 500, "rent_desc": "300-800/月", "medical_score": 2.0, "transport_score": 3.0, "living_score": 3.0, "elderly_score": 75, "category": "避暑", "tags": "九华山,低房价,生态好", "description": "池州有九华山风景区，空气质量极好，农村租房每月仅需300-500元。", "hospitals_3a": 1, "has_high_speed_rail": 1, "airport_distance": 120, "image_url": ""},
    {"name": "黟县", "province": "安徽", "lat": 29.92, "lng": 117.94, "altitude": 180, "summer_temp": "26℃", "winter_temp": "3℃", "air_quality": "优", "humidity": "68%", "rent_avg": 400, "rent_desc": "200-600/月", "medical_score": 1.5, "transport_score": 2.0, "living_score": 2.5, "elderly_score": 72, "category": "避暑", "tags": "宏村,西递,古村落,极低房价", "description": "黟县有宏村西递世界遗产，古村落环境优美，农村租房极便宜，适合喜欢古村生活的老人。", "hospitals_3a": 0, "has_high_speed_rail": 0, "airport_distance": 150, "image_url": ""},
    {"name": "休宁", "province": "安徽", "lat": 29.78, "lng": 118.19, "altitude": 200, "summer_temp": "26℃", "winter_temp": "3℃", "air_quality": "优", "humidity": "68%", "rent_avg": 400, "rent_desc": "200-600/月", "medical_score": 1.5, "transport_score": 2.5, "living_score": 2.5, "elderly_score": 73, "category": "避暑", "tags": "齐云山,状元县,农村养老", "description": "休宁是中国第一状元县，齐云山脚下环境优美，农村租房便宜，适合长期康养。", "hospitals_3a": 0, "has_high_speed_rail": 1, "airport_distance": 120, "image_url": ""},
    {"name": "绩溪", "province": "安徽", "lat": 30.07, "lng": 118.58, "altitude": 200, "summer_temp": "26℃", "winter_temp": "3℃", "air_quality": "优", "humidity": "68%", "rent_avg": 500, "rent_desc": "300-800/月", "medical_score": 1.5, "transport_score": 3.0, "living_score": 2.5, "elderly_score": 74, "category": "避暑", "tags": "徽杭古道,龙川,低房价", "description": "绩溪是徽杭古道起点，徽派建筑精美，生活成本极低，适合避暑长住。", "hospitals_3a": 0, "has_high_speed_rail": 1, "airport_distance": 100, "image_url": ""},
    {"name": "泾县", "province": "安徽", "lat": 30.69, "lng": 118.41, "altitude": 80, "summer_temp": "26℃", "winter_temp": "4℃", "air_quality": "优", "humidity": "68%", "rent_avg": 400, "rent_desc": "200-600/月", "medical_score": 1.5, "transport_score": 2.5, "living_score": 2.5, "elderly_score": 73, "category": "避暑", "tags": "桃花潭,宣纸,农村养老", "description": "泾县是宣纸原产地，桃花潭山水如画，农村房租极低，适合喜欢田园生活的老人。", "hospitals_3a": 0, "has_high_speed_rail": 0, "airport_distance": 110, "image_url": ""},
    {"name": "歙县", "province": "安徽", "lat": 29.86, "lng": 118.43, "altitude": 130, "summer_temp": "26℃", "winter_temp": "3℃", "air_quality": "优", "humidity": "68%", "rent_avg": 500, "rent_desc": "300-800/月", "medical_score": 1.5, "transport_score": 3.0, "living_score": 3.0, "elderly_score": 74, "category": "避暑", "tags": "徽州古城,牌坊,低房价", "description": "歙县是徽州古城所在地，历史文化底蕴深厚，房价低生活慢。", "hospitals_3a": 0, "has_high_speed_rail": 0, "airport_distance": 100, "image_url": ""},
    {"name": "安吉", "province": "浙江", "lat": 30.63, "lng": 119.68, "altitude": 150, "summer_temp": "26℃", "winter_temp": "4℃", "air_quality": "优", "humidity": "70%", "rent_avg": 1000, "rent_desc": "600-1500/月", "medical_score": 2.5, "transport_score": 3.5, "living_score": 3.5, "elderly_score": 80, "category": "避暑", "tags": "竹海,大竹海,乡村养老", "description": "安吉是中国竹乡，森林覆盖率高，夏季凉爽，乡村民宿产业发展成熟。", "hospitals_3a": 1, "has_high_speed_rail": 1, "airport_distance": 90, "image_url": ""},
    {"name": "桐庐", "province": "浙江", "lat": 29.79, "lng": 119.69, "altitude": 50, "summer_temp": "27℃", "winter_temp": "5℃", "air_quality": "优", "humidity": "70%", "rent_avg": 1200, "rent_desc": "800-1800/月", "medical_score": 2.5, "transport_score": 3.5, "living_score": 3.5, "elderly_score": 81, "category": "避暑", "tags": "富春江,山水,美丽乡村", "description": "桐庐有富春江山水美景，是《富春山居图》实景地，乡村旅居条件好。", "hospitals_3a": 1, "has_high_speed_rail": 1, "airport_distance": 80, "image_url": ""},
    {"name": "临安", "province": "浙江", "lat": 30.23, "lng": 119.72, "altitude": 100, "summer_temp": "26℃", "winter_temp": "4℃", "air_quality": "优", "humidity": "68%", "rent_avg": 1200, "rent_desc": "800-2000/月", "medical_score": 3.0, "transport_score": 3.5, "living_score": 3.5, "elderly_score": 82, "category": "避暑", "tags": "天目山,太湖源,杭州后花园", "description": "临安是杭州后花园，天目山自然保护区夏季凉爽，杭州高铁半小时可达。", "hospitals_3a": 2, "has_high_speed_rail": 1, "airport_distance": 60, "image_url": ""},
    {"name": "丽水", "province": "浙江", "lat": 28.45, "lng": 119.92, "altitude": 100, "summer_temp": "26℃", "winter_temp": "6℃", "air_quality": "优", "humidity": "72%", "rent_avg": 800, "rent_desc": "500-1200/月", "medical_score": 2.5, "transport_score": 3.0, "living_score": 3.0, "elderly_score": 78, "category": "避暑", "tags": "中国生态第一市,低房价,空气好", "description": "丽水是中国生态第一市，空气质量全国领先，房价低廉，适合康养。", "hospitals_3a": 2, "has_high_speed_rail": 1, "airport_distance": 100, "image_url": ""},
    {"name": "衢州", "province": "浙江", "lat": 28.97, "lng": 118.87, "altitude": 80, "summer_temp": "27℃", "winter_temp": "5℃", "air_quality": "优", "humidity": "70%", "rent_avg": 700, "rent_desc": "400-1000/月", "medical_score": 2.5, "transport_score": 3.5, "living_score": 3.0, "elderly_score": 77, "category": "避暑", "tags": "南孔圣地,低房价,美食", "description": "衢州是南孔圣地，房价在浙江最低之一，农村租房每月仅需400-600元。", "hospitals_3a": 2, "has_high_speed_rail": 1, "airport_distance": 120, "image_url": ""},
    {"name": "开化", "province": "浙江", "lat": 29.14, "lng": 118.41, "altitude": 150, "summer_temp": "26℃", "winter_temp": "5℃", "air_quality": "优", "humidity": "72%", "rent_avg": 500, "rent_desc": "300-800/月", "medical_score": 1.5, "transport_score": 2.5, "living_score": 2.5, "elderly_score": 74, "category": "避暑", "tags": "钱江源,国家公园,极低房价", "description": "开化是钱塘江源头，国家公园体制试点区，空气水质极好，农村租金极低。", "hospitals_3a": 0, "has_high_speed_rail": 0, "airport_distance": 150, "image_url": ""},
    {"name": "遂昌", "province": "浙江", "lat": 28.59, "lng": 119.28, "altitude": 200, "summer_temp": "25℃", "winter_temp": "5℃", "air_quality": "优", "humidity": "72%", "rent_avg": 500, "rent_desc": "300-700/月", "medical_score": 1.5, "transport_score": 2.0, "living_score": 2.5, "elderly_score": 72, "category": "避暑", "tags": "金矿公园,南尖岩,农村养老", "description": "遂昌有南尖岩梯田和金矿国家矿山公园，山区夏季凉爽，生活成本极低。", "hospitals_3a": 0, "has_high_speed_rail": 0, "airport_distance": 180, "image_url": ""},
    {"name": "兴义", "province": "贵州", "lat": 25.09, "lng": 104.90, "altitude": 1200, "summer_temp": "23℃", "winter_temp": "8℃", "air_quality": "优", "humidity": "65%", "rent_avg": 600, "rent_desc": "400-1000/月", "medical_score": 2.0, "transport_score": 3.0, "living_score": 3.0, "elderly_score": 78, "category": "避暑", "tags": "万峰林,马岭河,低房价", "description": "兴义有万峰林和马岭河峡谷，风景壮丽，房价极低，是贵州西南避暑宝地。", "hospitals_3a": 1, "has_high_speed_rail": 1, "airport_distance": 10, "image_url": ""},
    {"name": "安顺", "province": "贵州", "lat": 26.25, "lng": 105.95, "altitude": 1400, "summer_temp": "22℃", "winter_temp": "6℃", "air_quality": "优", "humidity": "65%", "rent_avg": 800, "rent_desc": "500-1200/月", "medical_score": 3.0, "transport_score": 3.5, "living_score": 3.5, "elderly_score": 81, "category": "避暑", "tags": "黄果树,龙宫,夏季凉爽", "description": "安顺有黄果树瀑布和龙宫景区，夏季凉爽，生活成本低，医疗在贵州算好。", "hospitals_3a": 2, "has_high_speed_rail": 1, "airport_distance": 10, "image_url": ""},
    {"name": "凯里", "province": "贵州", "lat": 26.58, "lng": 107.98, "altitude": 700, "summer_temp": "25℃", "winter_temp": "6℃", "air_quality": "优", "humidity": "70%", "rent_avg": 500, "rent_desc": "300-800/月", "medical_score": 2.0, "transport_score": 3.0, "living_score": 3.0, "elderly_score": 75, "category": "避暑", "tags": "黔东南,苗寨,侗寨,极低房价", "description": "凯里是黔东南州府，周边有西江千户苗寨和肇兴侗寨，少数民族文化丰富，农村租金极低。", "hospitals_3a": 1, "has_high_speed_rail": 1, "airport_distance": 10, "image_url": ""},
    {"name": "荔波", "province": "贵州", "lat": 25.41, "lng": 107.89, "altitude": 400, "summer_temp": "25℃", "winter_temp": "8℃", "air_quality": "优", "humidity": "75%", "rent_avg": 500, "rent_desc": "300-800/月", "medical_score": 1.5, "transport_score": 2.5, "living_score": 2.5, "elderly_score": 74, "category": "避暑", "tags": "小七孔,世界遗产,森林", "description": "荔波小七孔是世界自然遗产，森林覆盖率高，空气清新，农村房租极低。", "hospitals_3a": 0, "has_high_speed_rail": 0, "airport_distance": 150, "image_url": ""},
    {"name": "镇远", "province": "贵州", "lat": 27.05, "lng": 108.42, "altitude": 500, "summer_temp": "25℃", "winter_temp": "6℃", "air_quality": "优", "humidity": "68%", "rent_avg": 500, "rent_desc": "300-800/月", "medical_score": 1.5, "transport_score": 3.0, "living_score": 2.5, "elderly_score": 75, "category": "避暑", "tags": "镇远古城,舞阳河,低房价", "description": "镇远古城依山傍水，舞阳河穿城而过，夏季凉爽，生活成本低。", "hospitals_3a": 0, "has_high_speed_rail": 1, "airport_distance": 170, "image_url": ""},
    {"name": "雷山", "province": "贵州", "lat": 26.38, "lng": 108.08, "altitude": 900, "summer_temp": "24℃", "winter_temp": "5℃", "air_quality": "优", "humidity": "70%", "rent_avg": 400, "rent_desc": "200-600/月", "medical_score": 1.0, "transport_score": 2.0, "living_score": 2.0, "elderly_score": 71, "category": "避暑", "tags": "西江苗寨,雷公山,极低价", "description": "雷山有西江千户苗寨和雷公山自然保护区，农村租房每月最低200元。", "hospitals_3a": 0, "has_high_speed_rail": 0, "airport_distance": 200, "image_url": ""},
    {"name": "婺源", "province": "江西", "lat": 29.25, "lng": 117.86, "altitude": 100, "summer_temp": "26℃", "winter_temp": "5℃", "air_quality": "优", "humidity": "70%", "rent_avg": 600, "rent_desc": "400-1000/月", "medical_score": 1.5, "transport_score": 3.0, "living_score": 3.0, "elderly_score": 76, "category": "避暑", "tags": "油菜花,徽派建筑,低房价", "description": "婺源被誉为中国最美乡村，徽派建筑和田园风光闻名，适合喜欢乡村生活的老人。", "hospitals_3a": 0, "has_high_speed_rail": 1, "airport_distance": 130, "image_url": ""},
    {"name": "阳朔", "province": "广西", "lat": 24.78, "lng": 110.49, "altitude": 150, "summer_temp": "27℃", "winter_temp": "12℃", "air_quality": "优", "humidity": "72%", "rent_avg": 1000, "rent_desc": "600-1500/月", "medical_score": 2.0, "transport_score": 3.0, "living_score": 3.5, "elderly_score": 79, "category": "避暑", "tags": "漓江,山水,田园", "description": "阳朔漓江山水甲天下，田园风光优美，冬季温暖，适合候鸟旅居。", "hospitals_3a": 1, "has_high_speed_rail": 1, "airport_distance": 60, "image_url": ""},
    {"name": "巴马", "province": "广西", "lat": 24.15, "lng": 107.26, "altitude": 300, "summer_temp": "26℃", "winter_temp": "14℃", "air_quality": "优", "humidity": "70%", "rent_avg": 600, "rent_desc": "400-1000/月", "medical_score": 1.5, "transport_score": 2.0, "living_score": 2.5, "elderly_score": 76, "category": "避寒", "tags": "长寿之乡,康养,百魔洞", "description": "巴马是世界长寿之乡，每年有数万老人到此康养旅居，生活成本低。", "hospitals_3a": 0, "has_high_speed_rail": 0, "airport_distance": 100, "image_url": ""},
    {"name": "恩施", "province": "湖北", "lat": 30.30, "lng": 109.49, "altitude": 900, "summer_temp": "24℃", "winter_temp": "7℃", "air_quality": "优", "humidity": "68%", "rent_avg": 600, "rent_desc": "400-1000/月", "medical_score": 2.5, "transport_score": 3.0, "living_score": 3.0, "elderly_score": 77, "category": "避暑", "tags": "大峡谷,土家族,低房价", "description": "恩施大峡谷壮丽，土家族文化独特，夏季凉爽，房价极低。", "hospitals_3a": 2, "has_high_speed_rail": 1, "airport_distance": 5, "image_url": ""},
    {"name": "腾冲", "province": "云南", "lat": 25.02, "lng": 98.50, "altitude": 1640, "summer_temp": "23℃", "winter_temp": "12℃", "air_quality": "优", "humidity": "65%", "rent_avg": 1200, "rent_desc": "800-2000/月", "medical_score": 2.5, "transport_score": 2.5, "living_score": 3.5, "elderly_score": 80, "category": "避暑", "tags": "温泉,和顺古镇,银杏", "description": "腾冲有丰富温泉资源，和顺古镇宁静安逸，四季如春，是康养旅居热门地。", "hospitals_3a": 1, "has_high_speed_rail": 0, "airport_distance": 15, "image_url": ""},
]

cities_data.extend(new_cities)

new_houses = [
    {"_city_name": "宣城", "title": "宣城农村小院整租", "price": 500, "area": "120㎡", "house_type": "整院", "category": "农家乐", "contact": "美丽新乡村网站 010-56247008（全国农村房源信息平台，详见🌾农村页面）", "nearby_hospital": "镇卫生院2km", "nearby_market": "镇集市1km", "min_rent": "1个月", "rating": 4.3, "image_url": "", "description": "独门独院农村小院，有菜地，空气好，安静适合养老。"},
    {"_city_name": "宣城", "title": "宣城市区两室老房", "price": 700, "area": "60㎡", "house_type": "两室一厅", "category": "公寓", "contact": "到宣城后联系当地房产中介门店", "nearby_hospital": "市人民医院2km", "nearby_market": "中心菜市场500m", "min_rent": "1个月", "rating": 4.0, "image_url": "", "description": "市区老小区，生活方便，步行可达菜市场和超市。"},
    {"_city_name": "宣城", "title": "宣城泾县桃花潭农房", "price": 350, "area": "80㎡", "house_type": "两室", "category": "农家乐", "contact": "到桃花潭村后询问村委会或村口小卖部", "nearby_hospital": "泾县医院10km", "nearby_market": "桃花潭村集市500m", "min_rent": "1个月", "rating": 4.1, "image_url": "", "description": "桃花潭边老屋，李白诗意之地，每月只需350元。"},
    {"_city_name": "池州", "title": "池州九华山脚下农家院", "price": 400, "area": "80㎡", "house_type": "两室", "category": "农家乐", "contact": "到九华山后联系当地农家乐协会", "nearby_hospital": "九华山医院3km", "nearby_market": "镇上集市1km", "min_rent": "1个月", "rating": 4.5, "image_url": "", "description": "九华山脚下农家院，环境清幽，适合礼佛养老。"},
    {"_city_name": "池州", "title": "池州杏花村附近农居", "price": 350, "area": "60㎡", "house_type": "一室一厅", "category": "农家乐", "contact": "到杏花村后询问村里老人或村委", "nearby_hospital": "池州市医院8km", "nearby_market": "村口集市", "min_rent": "1个月", "rating": 4.0, "image_url": "", "description": "杏花村附近安静农居，有小院和菜地。"},
    {"_city_name": "黟县", "title": "黟县宏村民宿长租", "price": 600, "area": "50㎡", "house_type": "一室一厅", "category": "民宿", "contact": "到宏村后咨询宏村乡村客栈联盟（景区内215家民宿）", "nearby_hospital": "黟县人民医院3km", "nearby_market": "宏村菜市场500m", "min_rent": "1个月", "rating": 4.6, "image_url": "", "description": "宏村景区内民宿长租优惠，推开窗就是水墨徽州。"},
    {"_city_name": "黟县", "title": "黟县西递古宅改造房", "price": 500, "area": "40㎡", "house_type": "一室", "category": "民宿", "contact": "西递景区内有多家古宅民宿可实地看房", "nearby_hospital": "黟县医院4km", "nearby_market": "西递景区口", "min_rent": "1个月", "rating": 4.4, "image_url": "", "description": "西递古宅改造，徽派建筑体验。"},
    {"_city_name": "绩溪", "title": "绩溪农家土楼", "price": 400, "area": "70㎡", "house_type": "两室", "category": "农家乐", "contact": "到绩溪后联系龙川景区游客中心", "nearby_hospital": "镇卫生院2km", "nearby_market": "村口集市", "min_rent": "1个月", "rating": 4.2, "image_url": "", "description": "正宗徽派土楼，冬暖夏凉，周边有菜地和山林。"},
    {"_city_name": "绩溪", "title": "绩溪龙川景区农家", "price": 450, "area": "60㎡", "house_type": "两室", "category": "农家乐", "contact": "到龙川村后联系村委会或景区售票处", "nearby_hospital": "龙川卫生室500m", "nearby_market": "龙川集市300m", "min_rent": "1个月", "rating": 4.3, "image_url": "", "description": "龙川景区胡氏宗祠旁，古村落环境，安静清幽。"},
    {"_city_name": "安吉", "title": "安吉竹海农家乐", "price": 1000, "area": "45㎡", "house_type": "一室一厅", "category": "农家乐", "contact": "到安吉后咨询农家乐或通过携程/美团搜索长租", "nearby_hospital": "安吉人民医院5km", "nearby_market": "镇菜市场2km", "min_rent": "1个月", "rating": 4.7, "image_url": "", "description": "竹海深处的农家乐，空气清新，夏季凉爽，有食堂。"},
    {"_city_name": "安吉", "title": "安吉天荒坪山顶民宿", "price": 1200, "area": "35㎡", "house_type": "一室一厅", "category": "民宿", "contact": "天荒坪镇有多家民宿，到镇上后实地选择", "nearby_hospital": "安吉人民医院8km", "nearby_market": "天荒坪镇菜场", "min_rent": "1个月", "rating": 4.6, "image_url": "", "description": "海拔近千米，夏季盖棉被，星空绝美。"},
    {"_city_name": "桐庐", "title": "桐庐富春江畔农居", "price": 800, "area": "60㎡", "house_type": "两室一厅", "category": "民宿", "contact": "到桐庐后咨询当地民宿协会或村委", "nearby_hospital": "桐庐县医院4km", "nearby_market": "镇菜市场1km", "min_rent": "1个月", "rating": 4.5, "image_url": "", "description": "富春江畔农居改造民宿，有花园和茶室，环境优美。"},
    {"_city_name": "桐庐", "title": "桐庐芦茨村民宿", "price": 1000, "area": "40㎡", "house_type": "一室一厅", "category": "民宿", "contact": "到芦茨村后实地看房，村里很多民宿可长租", "nearby_hospital": "桐庐县医院6km", "nearby_market": "芦茨村口", "min_rent": "1个月", "rating": 4.7, "image_url": "", "description": "芦茨湾畔，《向往的生活》取景地风格。"},
    {"_city_name": "衢州", "title": "衢州农村整院", "price": 500, "area": "100㎡", "house_type": "整院", "category": "农家乐", "contact": "到衢州后到村里询问村委会", "nearby_hospital": "镇卫生院1km", "nearby_market": "村菜市场500m", "min_rent": "1个月", "rating": 4.3, "image_url": "", "description": "独院农房，有菜地和果树，适合喜欢种菜养花的老人。"},
    {"_city_name": "衢州", "title": "衢州古城边公寓", "price": 700, "area": "50㎡", "house_type": "一室一厅", "category": "公寓", "contact": "到衢州后联系当地房产中介", "nearby_hospital": "衢州市医院2km", "nearby_market": "南湖菜场500m", "min_rent": "1个月", "rating": 4.1, "image_url": "", "description": "靠近古城，生活便利，适合短期旅居。"},
    {"_city_name": "丽水", "title": "丽水松阳古村民宿", "price": 600, "area": "40㎡", "house_type": "一室一厅", "category": "民宿", "contact": "到松阳后走访陈家铺/杨家堂等古村落，村内有民宿", "nearby_hospital": "松阳县医院6km", "nearby_market": "古村村口", "min_rent": "1个月", "rating": 4.6, "image_url": "", "description": "松阳被《中国国家地理》誉为最后的江南秘境，古村落民宿体验。"},
    {"_city_name": "丽水", "title": "丽水云和梯田农家", "price": 500, "area": "50㎡", "house_type": "一室一厅", "category": "农家乐", "contact": "到云和梯田景区后咨询游客中心或农家乐", "nearby_hospital": "云和县医院10km", "nearby_market": "梯田景区口", "min_rent": "1个月", "rating": 4.4, "image_url": "", "description": "云和梯田观景房，云雾缭绕如仙境。"},
    {"_city_name": "遂昌", "title": "遂昌高坪避暑农居", "price": 400, "area": "50㎡", "house_type": "一室一厅", "category": "农家乐", "contact": "到高坪乡后联系乡政府或村里老人", "nearby_hospital": "镇卫生院3km", "nearby_market": "村便利店", "min_rent": "1个月", "rating": 4.4, "image_url": "", "description": "高海拔山区农居，夏季需盖棉被，是天然避暑胜地。"},
    {"_city_name": "兴义", "title": "兴义万峰林民宿", "price": 600, "area": "40㎡", "house_type": "一室一厅", "category": "民宿", "contact": "到万峰林景区后纳灰村有很多民宿可实地选择", "nearby_hospital": "兴义市医院5km", "nearby_market": "万峰林集市1km", "min_rent": "1个月", "rating": 4.8, "image_url": "", "description": "万峰林景区内，推窗见峰林，田园风光绝美。"},
    {"_city_name": "兴义", "title": "兴义马岭河旁农房", "price": 400, "area": "60㎡", "house_type": "两室", "category": "农家乐", "contact": "到马岭镇后询问当地村民", "nearby_hospital": "兴义市医院6km", "nearby_market": "马岭镇集市1km", "min_rent": "1个月", "rating": 4.2, "image_url": "", "description": "马岭河峡谷附近，空气清新，房租极低。"},
    {"_city_name": "安顺", "title": "安顺黄果树附近农房", "price": 500, "area": "60㎡", "house_type": "两室", "category": "农家乐", "contact": "到黄果树后咨询景区周边村民", "nearby_hospital": "镇卫生院2km", "nearby_market": "镇集市1km", "min_rent": "1个月", "rating": 4.2, "image_url": "", "description": "距黄果树瀑布5公里，空气好，房租极低。"},
    {"_city_name": "安顺", "title": "安顺市区两室电梯房", "price": 800, "area": "65㎡", "house_type": "两室一厅", "category": "公寓", "contact": "到安顺后联系当地房产中介", "nearby_hospital": "安顺市医院1km", "nearby_market": "市区菜场300m", "min_rent": "1个月", "rating": 4.3, "image_url": "", "description": "市中心电梯房，生活便利，适合长住。"},
    {"_city_name": "凯里", "title": "凯里西江苗寨长租房", "price": 500, "area": "30㎡", "house_type": "单间", "category": "民宿", "contact": "到西江千户苗寨后联系景区客栈协会", "nearby_hospital": "凯里市医院35km", "nearby_market": "苗寨集市200m", "min_rent": "1个月", "rating": 4.5, "image_url": "", "description": "西江苗寨观景台附近，吊脚楼体验，适合喜欢民族文化的老人。"},
    {"_city_name": "凯里", "title": "凯里雷山西江千户苗寨", "price": 400, "area": "25㎡", "house_type": "单间", "category": "民宿", "contact": "到雷山县后联系西江镇旅游接待中心", "nearby_hospital": "雷山县医院15km", "nearby_market": "苗寨菜市场100m", "min_rent": "1个月", "rating": 4.4, "image_url": "", "description": "苗寨半山腰单间，观景绝佳，体验苗族生活。"},
    {"_city_name": "镇远", "title": "镇远古城河边民居", "price": 500, "area": "40㎡", "house_type": "一室", "category": "民宿", "contact": "到镇远后沿舞阳河两岸有大量民宿可实地看房", "nearby_hospital": "镇远县医院2km", "nearby_market": "古城菜市场500m", "min_rent": "1个月", "rating": 4.5, "image_url": "", "description": "舞阳河边吊脚楼，推窗见景，古城生活安逸。"},
    {"_city_name": "婺源", "title": "婺源李坑写生小院", "price": 500, "area": "40㎡", "house_type": "一室", "category": "民宿", "contact": "婺源鄣山村云上民宿 余先生 17687932030（微信同号）", "nearby_hospital": "婺源县医院5km", "nearby_market": "李坑村菜市场300m", "min_rent": "1个月", "rating": 4.6, "image_url": "", "description": "李坑景区内小院，适合喜欢画画和安静的老人。"},
    {"_city_name": "婺源", "title": "婺源篁岭晒秋民宿", "price": 600, "area": "35㎡", "house_type": "一室一厅", "category": "民宿", "contact": "到篁岭景区后咨询景区内民宿", "nearby_hospital": "婺源县医院8km", "nearby_market": "篁岭景区口", "min_rent": "1个月", "rating": 4.7, "image_url": "", "description": "篁岭景区内，晒秋景观房，秋季最美。"},
    {"_city_name": "阳朔", "title": "阳朔遇龙河畔农居", "price": 1000, "area": "50㎡", "house_type": "一室一厅", "category": "民宿", "contact": "遇龙河竹蔸寨是民宿村，到村后多家可选", "nearby_hospital": "阳朔县医院4km", "nearby_market": "遇龙河集市1km", "min_rent": "1个月", "rating": 4.7, "image_url": "", "description": "遇龙河畔，田园风光，骑行散步都方便。"},
    {"_city_name": "阳朔", "title": "阳朔西街附近公寓", "price": 1200, "area": "45㎡", "house_type": "一室一厅", "category": "公寓", "contact": "到阳朔后联系当地房产中介", "nearby_hospital": "阳朔县医院1km", "nearby_market": "西街菜市场300m", "min_rent": "1个月", "rating": 4.3, "image_url": "", "description": "阳朔县城中心，生活便利，交通方便。"},
    {"_city_name": "巴马", "title": "巴马坡月村康养房", "price": 800, "area": "35㎡", "house_type": "一室一厅", "category": "康养社区", "contact": "巴马河源养生公寓 0771-7711853", "nearby_hospital": "村医务室200m", "nearby_market": "坡月菜市场500m", "min_rent": "3个月", "rating": 4.4, "image_url": "", "description": "巴马坡月村，每年数万老人聚集，有食堂和活动中心。"},
    {"_city_name": "巴马", "title": "巴马百魔洞附近农居", "price": 600, "area": "30㎡", "house_type": "单间", "category": "农家乐", "contact": "甲篆镇坡月村委（到村后实地看房最可靠）", "nearby_hospital": "村卫生室1km", "nearby_market": "百魔洞集市500m", "min_rent": "1个月", "rating": 4.2, "image_url": "", "description": "百魔洞附近，每天可去洞口吸氧。"},
    {"_city_name": "恩施", "title": "恩施大峡谷农家乐", "price": 500, "area": "50㎡", "house_type": "一室一厅", "category": "农家乐", "contact": "恩施大峡谷桂元农家乐 13402775929", "nearby_hospital": "镇卫生院3km", "nearby_market": "峡谷集市1km", "min_rent": "1个月", "rating": 4.5, "image_url": "", "description": "恩施大峡谷景区旁农家乐，夏季凉爽，土家饭菜可口。"},
    {"_city_name": "恩施", "title": "恩施土司城旁民宿", "price": 700, "area": "40㎡", "house_type": "一室一厅", "category": "民宿", "contact": "恩施大峡谷景区服务热线 400-0718-126", "nearby_hospital": "恩施市医院3km", "nearby_market": "土司城菜场", "min_rent": "1个月", "rating": 4.3, "image_url": "", "description": "土司城附近民宿，交通便利。"},
]

new_reviews = [
    {"_city_name": "宣城", "user_name": "老陈", "rating_living": 4, "rating_medical": 2, "rating_market": 3, "rating_elderly": 4, "content": "宣城农村住了一个月，房租才500，空气太好了。就是离医院远了点，小病去镇卫生院还行。", "stay_duration": "1个月"},
    {"_city_name": "黟县", "user_name": "画家老李", "rating_living": 5, "rating_medical": 1, "rating_market": 3, "rating_elderly": 4, "content": "黟县宏村住了两个月，天天画画写生，房租600一月，太值了。一定要自己备好常用药。", "stay_duration": "2个月"},
    {"_city_name": "安吉", "user_name": "张老师", "rating_living": 5, "rating_medical": 2, "rating_market": 3, "rating_elderly": 4, "content": "安吉竹海太美了，夏天比城里凉快很多。农家乐包吃住每月1800，性价比很高。", "stay_duration": "1个月"},
    {"_city_name": "兴义", "user_name": "刘叔", "rating_living": 5, "rating_medical": 2, "rating_market": 3, "rating_elderly": 5, "content": "兴义万峰林真是养老宝地，夏天不热，风景绝美，房租600。当地老乡很淳朴。", "stay_duration": "3个月"},
    {"_city_name": "凯里", "user_name": "摄影爱好者老赵", "rating_living": 4, "rating_medical": 2, "rating_market": 3, "rating_elderly": 4, "content": "凯里苗寨住了半个月，民族风情浓郁，东西便宜。就是医疗条件差，大病得去凯里市里。", "stay_duration": "半个月"},
    {"_city_name": "婺源", "user_name": "吴阿姨", "rating_living": 5, "rating_medical": 2, "rating_market": 3, "rating_elderly": 5, "content": "婺源的春天美得像画一样，村里人都很友好。农村生活简单，适合想清净的老人。", "stay_duration": "1个月"},
    {"_city_name": "巴马", "user_name": "候鸟老王", "rating_living": 4, "rating_medical": 3, "rating_market": 3, "rating_elderly": 4, "content": "巴马坡月村住了半年，好多东北老人在那，大家一起做操散步。水质确实好，房租800。", "stay_duration": "6个月"},
    {"_city_name": "恩施", "user_name": "周姐", "rating_living": 4, "rating_medical": 3, "rating_market": 3, "rating_elderly": 4, "content": "恩施大峡谷夏天真是凉快，房租500农家乐还包饭。土家族人热情好客。", "stay_duration": "2个月"},
    {"_city_name": "桐庐", "user_name": "老钱夫妇", "rating_living": 5, "rating_medical": 3, "rating_market": 4, "rating_elderly": 5, "content": "桐庐富春江边的民宿，每天看看山水，去杭州也近。适合有点预算但想住环境好的老人。", "stay_duration": "2个月"},
    {"_city_name": "阳朔", "user_name": "陈叔", "rating_living": 4, "rating_medical": 2, "rating_market": 3, "rating_elderly": 4, "content": "阳朔遇龙河骑车太舒服了，冬天也比北方暖和。房租1000比三亚便宜太多。", "stay_duration": "3个月"},
    {"_city_name": "安顺", "user_name": "杨老", "rating_living": 5, "rating_medical": 3, "rating_market": 3, "rating_elderly": 4, "content": "安顺夏天真是太舒服了，黄果树瀑布看了好几次。房租便宜，生活成本低。", "stay_duration": "2个月"},
    {"_city_name": "衢州", "user_name": "小徐妈妈", "rating_living": 4, "rating_medical": 2, "rating_market": 3, "rating_elderly": 4, "content": "衢州农村整院每月500，种了点菜养了鸡，过上了理想的退休生活。", "stay_duration": "4个月"},
]

houses_data = [
    {"city_id": 1, "title": "六盘水钟山区温馨一室", "price": 1200, "area": "35㎡", "house_type": "一室一厅", "category": "公寓", "contact": "到六盘水后联系当地房产中介（钟山区多家）", "nearby_hospital": "市人民医院1.5km", "nearby_market": "明湖菜市场500m", "min_rent": "1个月", "rating": 4.5, "image_url": "", "description": "精装修公寓，家电齐全，拎包入住，安静舒适。"},
    {"city_id": 1, "title": "六盘水万达广场两室", "price": 1800, "area": "60㎡", "house_type": "两室一厅", "category": "公寓", "contact": "到六盘水后联系当地房产中介", "nearby_hospital": "市人民医院2km", "nearby_market": "万达超市300m", "min_rent": "1个月", "rating": 4.7, "image_url": "", "description": "位于万达广场旁，生活便利，家电齐全，适合老两口。"},
    {"city_id": 2, "title": "昆明滇池边康养公寓", "price": 2800, "area": "45㎡", "house_type": "一室一厅", "category": "康养社区", "contact": "到昆明后通过安居客/58同城搜索滇池周边租房", "nearby_hospital": "市人民医院1km", "nearby_market": "滇池卫城菜市场800m", "min_rent": "3个月", "rating": 4.8, "image_url": "", "description": "滇池边康养社区，配套完善，有食堂、活动室、医疗站。"},
    {"city_id": 2, "title": "昆明官渡区两室好房", "price": 2200, "area": "55㎡", "house_type": "两室一厅", "category": "公寓", "contact": "到昆明后联系当地房产中介", "nearby_hospital": "官渡区医院1.2km", "nearby_market": "官渡菜市场600m", "min_rent": "1个月", "rating": 4.6, "image_url": "", "description": "小区环境好，交通便利，附近有超市和菜市场。"},
    {"city_id": 7, "title": "西双版纳告庄西双景民宿", "price": 3000, "area": "50㎡", "house_type": "一室一厅", "category": "民宿", "contact": "告庄西双景孔雀楼公寓出租 13820125824", "nearby_hospital": "州人民医院3km", "nearby_market": "告庄夜市500m", "min_rent": "1个月", "rating": 4.6, "image_url": "", "description": "告庄西双景内，热带风格装修，楼下就是夜市和超市。"},
    {"city_id": 7, "title": "景洪市区两室公寓", "price": 2500, "area": "65㎡", "house_type": "两室一厅", "category": "公寓", "contact": "到景洪后联系当地房产中介", "nearby_hospital": "市人民医院2km", "nearby_market": "景洪农贸市场800m", "min_rent": "1个月", "rating": 4.5, "image_url": "", "description": "景洪市中心，生活便利，步行可达菜市场。"},
    {"city_id": 9, "title": "北海银滩旁海景公寓", "price": 2000, "area": "40㎡", "house_type": "一室一厅", "category": "公寓", "contact": "到北海后通过58同城/安居客搜索银滩租房", "nearby_hospital": "市人民医院3km", "nearby_market": "侨港菜市场1km", "min_rent": "1个月", "rating": 4.7, "image_url": "", "description": "银滩旁海景房，阳台看海，适合冬季过冬。"},
    {"city_id": 9, "title": "北海市中心两室", "price": 1500, "area": "70㎡", "house_type": "两室一厅", "category": "公寓", "contact": "到北海后联系当地房产中介", "nearby_hospital": "市中医院1.5km", "nearby_market": "文明路菜市场300m", "min_rent": "1个月", "rating": 4.4, "image_url": "", "description": "市中心老小区，生活便利，菜市场就在楼下。"},
    {"city_id": 12, "title": "大理古城旁白族小院", "price": 2500, "area": "80㎡", "house_type": "两室一厅", "category": "民宿", "contact": "大理古城才村码头民宿 18692222801", "nearby_hospital": "市人民医院4km", "nearby_market": "古城菜市场1km", "min_rent": "1个月", "rating": 4.9, "image_url": "", "description": "白族传统小院，有花园和茶室，环境清幽。"},
    {"city_id": 12, "title": "大理洱海边海景房", "price": 3000, "area": "50㎡", "house_type": "一室一厅", "category": "民宿", "contact": "到喜洲后咨询当地客栈或找村内招贴", "nearby_hospital": "市第二人民医院5km", "nearby_market": "喜洲菜市场2km", "min_rent": "1个月", "rating": 4.8, "image_url": "", "description": "洱海边一线海景房，看日出日落，适合旅居。"},
    {"city_id": 14, "title": "三亚湾海景康养公寓", "price": 5000, "area": "55㎡", "house_type": "一室一厅", "category": "康养社区", "contact": "候鸟暖巢康养中心 13752108677", "nearby_hospital": "三亚中心医院2km", "nearby_market": "第三菜市场1km", "min_rent": "3个月", "rating": 4.7, "image_url": "", "description": "三亚湾一线海景，康养社区配套齐全，有食堂和医疗服务。"},
    {"city_id": 14, "title": "三亚市区两室出租", "price": 3500, "area": "70㎡", "house_type": "两室一厅", "category": "公寓", "contact": "三亚养老服务中心 0898-32350800", "nearby_hospital": "市人民医院1.5km", "nearby_market": "港华市场500m", "min_rent": "1个月", "rating": 4.5, "image_url": "", "description": "市区地段好，生活方便，步行可达超市和医院。"},
    {"city_id": 15, "title": "成都锦里旁老小区两室", "price": 2800, "area": "60㎡", "house_type": "两室一厅", "category": "公寓", "contact": "58同城搜索「成都武侯区租房」", "nearby_hospital": "华西医院2km", "nearby_market": "玉林菜市场500m", "min_rent": "1个月", "rating": 4.6, "image_url": "", "description": "紧邻锦里，老成都生活氛围浓厚，美食众多。"},
    {"city_id": 15, "title": "成都温江康养社区", "price": 3200, "area": "50㎡", "house_type": "一室一厅", "category": "康养社区", "contact": "康嘉逸居旅居养老公寓 400-8778562", "nearby_hospital": "温江区医院1km", "nearby_market": "社区食堂", "min_rent": "3个月", "rating": 4.8, "image_url": "", "description": "专业康养社区，配套医疗站、活动室、花园。"},
    {"city_id": 52, "title": "海口龙华区一室公寓", "price": 2500, "area": "40㎡", "house_type": "一室一厅", "category": "公寓", "contact": "珊瑚老年网 0898-68964991", "nearby_hospital": "海南医学院附属医院1.5km", "nearby_market": "龙华菜市场500m", "min_rent": "1个月", "rating": 4.5, "image_url": "", "description": "龙华区中心地段，交通便利，生活配套齐全。"},
    {"city_id": 52, "title": "海口西海岸海景房", "price": 3500, "area": "55㎡", "house_type": "一室一厅", "category": "公寓", "contact": "珊瑚老年网 0898-68964991", "nearby_hospital": "省人民医院3km", "nearby_market": "西海岸超市1km", "min_rent": "1个月", "rating": 4.6, "image_url": "", "description": "西海岸海景公寓，环境优美，适合过冬养老。"},
]

reviews_data = [
    {"city_id": 1, "user_name": "王大爷", "rating_living": 5, "rating_medical": 4, "rating_market": 5, "rating_elderly": 5, "content": "我和老伴去年住了45天，夏天非常舒服，晚上还要盖被子。菜市场东西便宜新鲜。", "stay_duration": "45天"},
    {"city_id": 1, "user_name": "李阿姨", "rating_living": 5, "rating_medical": 3, "rating_market": 4, "rating_elderly": 4, "content": "空气好，夏天凉爽，就是海拔高，刚来前两天有点喘。建议老人来之前检查一下心肺。", "stay_duration": "2个月"},
    {"city_id": 2, "user_name": "老张", "rating_living": 5, "rating_medical": 5, "rating_market": 5, "rating_elderly": 5, "content": "昆明住了三年了，医疗好，气候好，去哪都方便。推荐给所有想来云南养老的朋友。", "stay_duration": "3年"},
    {"city_id": 7, "user_name": "赵叔", "rating_living": 4, "rating_medical": 3, "rating_market": 4, "rating_elderly": 4, "content": "冬天很暖和，水果特别多，就是夏天太热了。来这里过冬非常好。", "stay_duration": "3个月"},
    {"city_id": 9, "user_name": "陈阿姨", "rating_living": 4, "rating_medical": 3, "rating_market": 4, "rating_elderly": 4, "content": "北海房价便宜，海鲜多，冬天比湖南暖和多了。适合预算不多的老人。", "stay_duration": "6个月"},
    {"city_id": 12, "user_name": "老刘", "rating_living": 5, "rating_medical": 3, "rating_market": 4, "rating_elderly": 5, "content": "大理古城生活太美了，每天散散步，看看苍山洱海。医疗一般，但小病没问题。", "stay_duration": "2个月"},
    {"city_id": 14, "user_name": "老周夫妇", "rating_living": 4, "rating_medical": 4, "rating_market": 4, "rating_elderly": 4, "content": "三亚过冬确实舒服，就是房租贵了点。医疗交通都不错。", "stay_duration": "4个月"},
    {"city_id": 15, "user_name": "马阿姨", "rating_living": 5, "rating_medical": 5, "rating_market": 5, "rating_elderly": 5, "content": "成都太安逸了，华西医院就在旁边，看病方便，美食多。就是夏天有点热。", "stay_duration": "1年"},
    {"city_id": 16, "user_name": "徐叔", "rating_living": 4, "rating_medical": 4, "rating_market": 4, "rating_elderly": 4, "content": "大连夏天很舒服，海边走走，空气好。医疗也好，推荐。", "stay_duration": "2个月"},
    {"city_id": 52, "user_name": "黄阿姨", "rating_living": 4, "rating_medical": 4, "rating_market": 4, "rating_elderly": 4, "content": "海口过冬很好，医疗交通都方便，就是夏天湿热。", "stay_duration": "5个月"},
]

houses_data.extend(new_houses)
reviews_data.extend(new_reviews)

guides_data = [
    {"city_id": None, "category": "避坑攻略", "title": "候鸟旅居常见非法集资骗局", "source": "综合整理",
     "content": "近年来多地出现以'候鸟养老''旅居康养'为名的非法集资案件。不法分子以预订床位、会员充值、养老项目投资为名，承诺高额返利，最终资金链断裂。\n\n【如何识别】\n1. 承诺年化回报超过6%的基本可疑\n2. 要求一次性缴纳大额会员费/床位费\n3. 没有实体经营场所或项目地点模糊\n4. 宣传'政府支持''央企合作'却无法提供证明\n\n【如何防范】\n• 理性看待'高回报养老'，天上不会掉馅饼\n• 查看企业工商信息，核实是否具备养老资质\n• 签订合同前咨询子女或律师\n• 警惕熟人介绍、免费旅游、免费体检等营销手段",
     "tags": "防骗,非法集资,会员陷阱"},
    {"city_id": None, "category": "避坑攻略", "title": "云南旅居民宿签约避坑指南", "source": "综合整编",
     "content": "云南是候鸟老人最热门的旅居地之一，但民宿短租市场乱象较多。\n\n【签约前必查】\n1. 确认房东产权证明，避免二房东转租纠纷\n2. 明确水电气网费用谁承担，很多民宿另收'服务费''清洁费'\n3. 拍照记录房屋现状，避免退房时被索赔\n\n【常见陷阱】\n• 线上图片与实物严重不符——建议实地看房或视频验房\n• 口头承诺与合同不一致——所有承诺必须写入合同\n• 入住后临时涨价——签订长租合同时明确租金有效期\n• 押金退还困难——在合同中明确押金退还条件和时间\n\n【云南特别提醒】\n大理、丽江等地旅游旺季价格翻倍，建议长租在淡季签合同锁定价格。西双版纳冬季房源紧张，需提前1-2个月预订。",
     "tags": "签约,云南,民宿,租房"},
    {"city_id": None, "category": "避坑攻略", "title": "候鸟老人异地医保备案指南", "source": "国家医保局政策",
     "content": "异地就医直接结算是国家惠民政策，候鸟老人出行前务必办理异地就医备案。\n\n【备案流程】\n1. 下载'国家医保服务平台'APP或微信小程序\n2. 点击'异地备案'，选择'为自己备案'或'为他人备案'\n3. 填写备案信息：备案类型选'异地长期居住人员'或'临时外出就医'\n4. 选择就医地（如去大理就选云南省大理州）\n5. 提交后通常1-2个工作日审核通过\n\n【注意事项】\n• 长期居住备案（超过6个月）报销比例更高\n• 临时备案有效期为6个月，到期需重新备案\n• 备案后可在就医地所有开通异地结算的医院直接结算\n• 门诊慢特病（高血压、糖尿病等）需单独申请备案\n• 建议出发前在本地医院备足慢性病常用药\n• 保存好所有就医发票和病历，以防结算异常",
     "tags": "医保,异地就医,备案,医疗"},
    {"city_id": None, "category": "出行攻略", "title": "六盘水避暑旅居全攻略（中国凉都）", "source": "综合整理",
     "content": "六盘水夏季平均气温仅22℃，被称为'中国凉都'，是夏季避暑首选地。\n\n【最佳时间】6月-9月，7-8月最凉爽但游客最多\n【交通】\n• 高铁：贵阳北→六盘水约1.5小时\n• 飞机：六盘水月照机场，北京/上海/广州有直飞\n• 市内公交发达，出租车起步价7元\n\n【住宿推荐】\n• 钟山区市区：生活便利，月租1200-1800元\n• 明湖湿地公园附近：环境优美，适合散步\n• 梅花山景区周边：海拔高更凉快，适合短期\n\n【注意事项】\n⚠️ 六盘水海拔1800米，初到此地可能有轻微高原反应\n⚠️ 建议前两天减少运动量，多喝水，避免饮酒\n⚠️ 早晚温差大（10-25℃），需准备薄外套\n⚠️ 夏季紫外线强，注意防晒\n\n【生活贴士】\n• 当地菜场羊肉粉、烙锅是特色美食\n• 市区有三家三甲医院，医疗基本保障\n• 当地社区有丰富的广场舞和山歌活动",
     "tags": "六盘水,避暑,凉都,贵州"},
    {"city_id": None, "category": "出行攻略", "title": "大理慢生活旅居指南", "source": "综合整理",
     "content": "大理以苍山洱海、古城韵味和慢节奏生活吸引大量候鸟老人。\n\n【最佳季节】\n• 春季（3-5月）：气候最佳，花开满城\n• 夏季（6-8月）：凉爽舒适，但时有阵雨\n• 秋季（9-11月）：秋高气爽，最适合旅居\n• 冬季温暖，但不适合怕冷的人\n\n【居住区域选择】\n• 大理古城：生活便利，热闹但晚上较吵\n• 才村/龙龛码头：洱海边，安静风景好\n• 喜洲古镇：田园风光，房租更低\n• 下关市区：配套设施完善，离医院近\n\n【生活成本参考】\n• 房租：古城/洱海边1500-3000元/月，喜洲800-1500元\n• 菜市场物价：比一线城市低30-50%\n• 每月总开销（含房租）：1500-4000元\n\n【看病提醒】\n大理州人民医院是三甲医院，距离古城约5公里。建议备好常用药，慢性病药物可在市医院续方。",
     "tags": "大理,云南,慢生活,洱海"},
    {"city_id": None, "category": "出行攻略", "title": "西双版纳过冬旅居攻略", "source": "综合整理",
     "content": "西双版纳冬季平均气温20℃左右，是避寒过冬的热门目的地。\n\n【最佳时间】11月-次年3月，冬季温暖干燥\n【交通】\n• 飞机：西双版纳嘎洒机场，全国主要城市有直飞\n• 高铁：昆明→版纳约3.5小时（2023年开通）\n\n【居住区域】\n• 景洪市区：配套最完善，医院超市齐全\n• 告庄西双景：夜市繁华，适合短期体验\n• 勐腊/勐海：环境更原生态，房租更低\n\n【特别提醒】\n🌴 版纳紫外线极强，一年四季都要防晒\n🌴 蚊虫多，建议备好驱蚊用品和防蚊药物\n🌴 饮食偏酸辣，肠胃不好的老人需注意\n🌴 夏季太热（35℃+），建议冬季来避寒\n\n【生活贴士】\n• 水果丰富且便宜（尤其是芒果、菠萝、香蕉）\n• 当地少数民族节日多，每周都有赶摆（集市）\n• 景洪市医院和傣医院可满足基本医疗需求",
     "tags": "西双版纳,避寒,云南,冬季"},
    {"city_id": None, "category": "出行攻略", "title": "巴马长寿村康养旅居须知", "source": "综合整理",
     "content": "巴马是世界长寿之乡，每年有数万候鸟老人到此康养。\n\n【核心区域】\n• 坡月村：候鸟老人最集中，有食堂、活动中心\n• 百魔洞附近：地磁高，很多人每天去洞里坐一坐\n• 甲篆镇：配套设施相对完善\n\n【住宿情况】\n• 月租：400-1500元不等（取决于是否包吃）\n• 包吃住：单人间800-1500元/月\n• 建议选有食堂的住宿点，自己做饭不方便\n\n【医疗条件】\n⚠️ 巴马只有乡镇卫生院和村卫生室，大病需去百色市\n⚠️ 有高血压、心脏病等慢性病的老人需备足药品\n⚠️ 建议选择有医疗站的康养基地\n\n【生活提醒】\n• 巴马水质偏硬，建议喝桶装水\n• 当地经济较落后，生活设施不如城市便利\n• 雨季（5-8月）潮湿，衣物易发霉\n• 候鸟老人社群多，容易找到志同道合的朋友",
     "tags": "巴马,长寿,康养,广西"},
    {"city_id": None, "category": "出行攻略", "title": "海南过冬避寒全攻略", "source": "综合整理",
     "content": "海南是中国最热门的避寒过冬目的地，全岛气候温暖。\n\n【城市选择】\n• 三亚：最热门，冬季23-25℃，房租最高（3000-8000元/月）\n• 海口：省会配套全，医疗好，物价低，冬季20-22℃\n• 陵水/万宁：人少景美，性价比高\n• 琼海/文昌：生活节奏慢，适合长期居住\n• 东方市：房价最低，但配套相对落后\n\n【过冬建议】\n• 提前2-3个月预订长租房（9-10月开始找）\n• 三亚短租贵可考虑先住三亚玩，再搬去琼海/文昌长住\n• 海南高铁环岛，城市间交通方便\n\n【医疗提醒】\n• 三亚有4家三甲医院，海口有8家\n• 建议选住宿距医院3公里以内的房源\n• 异地就医备案提前办好\n\n【注意事项】\n🌴 台风季（7-10月）需关注天气预报\n🌴 冬季是旺季，物价房价都比平时贵\n🌴 潮湿，建议备除湿用品\n🌴 海鲜虽好但不要过量，注意肠胃",
     "tags": "海南,避寒,过冬,三亚,海口"},
    {"city_id": None, "category": "注意事项", "title": "农村旅居消防安全指南", "source": "综合整理",
     "content": "农村房屋普遍存在消防安全隐患，候鸟老人务必注意。\n\n【常见隐患】\n1. 电线老化、乱拉乱接——农村老房电路普遍老旧\n2. 使用煤炉/炭火取暖——一氧化碳中毒风险\n3. 厨房柴火堆放不当——容易引燃\n4. 缺少消防通道——万一火灾难逃生\n\n【安全建议】\n✅ 入住后检查电线和插座，老化的要求房东更换\n✅ 使用电热毯、取暖器时人走电断\n✅ 煤炉取暖一定要保持通风，安装一氧化碳报警器\n✅ 熟悉最近的卫生院和村委位置\n✅ 手机保存当地消防电话（119）和急救电话（120）\n✅ 建议自备小型灭火器和烟雾报警器",
     "tags": "安全,消防,农村租房"},
    {"city_id": None, "category": "注意事项", "title": "候鸟老人旅居健康管理建议", "source": "综合整理",
     "content": "随着年龄增长，旅居时健康管理尤为重要。\n\n【出发前准备】\n• 全面体检一次，特别是心脑血管检查\n• 备足至少3个月的慢性病用药\n• 准备常用药清单（药名、用法、用量）\n• 办理异地就医备案（非常重要）\n\n【旅居期间】\n• 海拔超过1500米的地区（如六盘水、大理、丽江），前3天避免剧烈运动\n• 高血压患者每天早晚各测一次血压\n• 注意当地气候变化，及时增减衣物\n• 饮食有度，避免生冷食物\n\n【应急准备】\n• 手机存储当地医院地址和联系方式\n• 随身携带急救药品（速效救心丸、硝酸甘油等）\n• 告知家人或朋友你的住址和行程\n• 加入当地候鸟老人群，互相照应\n\n【心理健康】\n旅居独居容易孤独，建议参加社区活动、广场舞、棋牌等社交活动，保持积极心态。",
     "tags": "健康,医疗,老人,安全"},
    {"city_id": None, "category": "注意事项", "title": "农村租房合同注意事项", "source": "综合整理",
     "content": "农村租房市场不规范，合同签订需格外谨慎。\n\n【必须明确的条款】\n1. 租金包含的费用（水电气网是否包含）\n2. 押金金额及退还条件\n3. 维修责任划分（家电家具坏了谁修）\n4. 提前解约的违约责任\n5. 房东身份证和房产证明\n\n【农村租房特别提示】\n• 很多农村租赁没有正式合同，建议自己写一份双方签字\n• 拍照/录像记录交房时的房屋状况\n• 明确禁止房东在租期内随意进入房间\n• 确认房屋空气质量，新装修房需通风\n• 询问周边是否安静（是否有养狗、办酒席等情况）\n\n【付款方式】\n• 尽量月付或季付，不要一次性付超过半年租金\n• 转账备注'XX房屋XX月租金及押金'\n• 保留转账记录和收据",
     "tags": "合同,租房,法律,农村"},
    {"city_id": None, "category": "避坑攻略", "title": "高原反应与海拔适应指南", "source": "综合整理",
     "content": "许多避暑城市海拔较高（1500-2400米），初到者需注意高原反应。\n\n【常见高反症状】\n头痛、失眠、气短、心跳加快、食欲减退\n\n【高风险城市】\n• 丽江（2400米）⚠️⚠️⚠️\n• 大理（1970米）⚠️⚠️\n• 六盘水（1800米）⚠️⚠️\n• 昆明（1890米）⚠️⚠️\n• 西昌（1500米）⚠️\n• 曲靖/玉溪（1700-1850米）⚠️\n\n【适应建议】\n✅ 到达前两天减少活动，多休息\n✅ 多喝水（每天2-3升），避免饮酒\n✅ 前三天不要洗热水澡（会加速血液循环增加心脏负担）\n✅ 房间保持通风\n✅ 可备红景天或氧气瓶（药店有售）\n\n【禁忌人群】\n❌ 严重高血压（150/100以上）不宜住海拔1500米以上\n❌ 心脏病、心衰患者谨慎前往高海拔地区\n❌ 有高原反应史的老人谨慎选择",
     "tags": "高原反应,海拔,健康,安全"},
    {"city_id": None, "category": "避坑攻略", "title": "康养社区/养老基地选择避坑", "source": "综合整理",
     "content": "近年来各地涌现大量'康养基地''养老社区'，鱼龙混杂。\n\n【选择标准】\n1. 查看营业执照和养老机构备案证明\n2. 实地考察后再缴费，不轻信宣传册\n3. 确认医疗配套：是否有医务室、距三甲医院多远\n4. 了解退出机制：如果不满意能否退款\n\n【常见问题】\n• '买会员'模式：预付几万到几十万买床位使用权——高风险\n• '分时度假'模式：宣传全国换住——实际很难兑现\n• '以房养老'模式：把房子抵押给公司——极度危险\n• '康养地产'模式：买养老公寓返租——跑路风险高\n\n【靠谱的康养方式】\n✅ 按月/季短租，灵活自由\n✅ 选择有口碑的连锁品牌\n✅ 先试住一周再决定是否长住\n✅ 老人之间互相打听口碑",
     "tags": "康养,养老社区,防骗,选择"},
    {"city_id": None, "category": "出行攻略", "title": "贵州避暑环线旅居推荐", "source": "综合整理",
     "content": "贵州夏季平均气温24℃左右，是避暑胜地，且消费水平低。\n\n【推荐路线】\n贵阳（2周）→ 安顺/黄果树（1周）→ 六盘水（2周）→ 兴义（1周）→ 荔波（1周）→ 黔东南凯里/镇远（2周）\n\n【各站特色】\n• 贵阳：交通枢纽，医疗好，先适应贵州气候\n• 安顺：黄果树瀑布，夏季凉爽，月租800-1200元\n• 六盘水：中国凉都，最凉快，月租1200-1800元\n• 兴义：万峰林壮丽，房租极低（600元）\n• 荔波：小七孔世界遗产，森林氧吧，房租500元\n• 凯里/镇远：苗族侗族文化，古镇风光，房租400-500元\n\n【交通】各城市间高铁/大巴方便，票价30-120元\n\n【注意事项】\n贵州气候湿润，衣物易发霉，建议带除湿袋。山区公路弯多，晕车老人备好晕车药。",
     "tags": "贵州,避暑,环线,夏季"},
    {"city_id": None, "category": "注意事项", "title": "海边城市居住注意事项", "source": "综合整理",
     "content": "海边环境宜人，但长期居住有几个注意事项。\n\n【潮湿问题】\n• 海边湿度普遍70-80%，衣物家具易发霉\n• 建议备除湿机或除湿袋\n• 衣物尽量挂放在通风处\n• 电子产品放置防潮箱\n\n【台风季】\n• 海南/广东/福建台风季为7-10月\n• 台风季期间储备3天左右的食品和饮用水\n• 关注当地气象预警，台风天不要外出\n• 选择建筑质量好的房子，避开危房\n\n【饮食注意】\n• 海鲜虽好但寒凉，脾胃虚弱的老人不宜多食\n• 海边水质偏软，长期饮用建议选桶装水\n• 热带水果糖分高，糖尿病患者需控制\n\n【其他】\n• 海边紫外线强，日常需防晒\n• 海风含盐分，空调外机等金属易生锈\n• 冬季海边风大，体感温度比实际温度低",
     "tags": "海边,潮湿,台风,居住"},
    {"city_id": None, "category": "出行攻略", "title": "长三角乡村旅居指南（皖南浙西）", "source": "综合整理",
     "content": "长三角地区的皖南和浙西山区是新兴的乡村旅居目的地，交通便利且环境优美。\n\n【推荐目的地】\n• 安徽宣城/泾县：徽派村落，月租400-600元\n• 安徽黟县/歙县：宏村西递世界遗产，月租400-600元\n• 浙江安吉：竹海之乡，月租800-1200元\n• 浙江桐庐：富春江山水，月租800-1200元\n• 浙江丽水/松阳：最后的江南秘境，月租500-800元\n• 江西婺源：中国最美乡村，月租400-800元\n\n【优势】\n✅ 高铁直达，从上海/杭州出发2-3小时\n✅ 医疗条件相对农村好，县级医院可达二甲\n✅ 气候温和，四季分明\n✅ 徽菜/浙菜口味清淡适合老人\n\n【交通建议】\n这些目的地大多有高铁站，建议坐高铁到最近的城市再转公交或打车。部分古村落不通公交，需包车进出。\n\n【注意事项】\n• 古村落多为木结构房屋，注意防火\n• 山区早晚温差大（10℃以上），备好衣物\n• 生活配套较大城市有所差距",
     "tags": "安徽,浙江,长三角,乡村,古村落"},
    {"city_id": None, "category": "避坑攻略", "title": "候鸟老人防骗手册（保健品/投资/旅游）", "source": "综合整理",
     "content": "候鸟老人独在异乡，容易成为不法分子的目标。\n\n【常见骗局类型】\n\n1️⃣ 保健品骗局\n• 以'免费体检''健康讲座'为名推销高价保健品\n• 常见话术：'专家推荐''央视报道''治愈案例'\n• 防范：认准'蓝帽子'标志，不轻信口头宣传\n\n2️⃣ 投资理财骗局\n• '旅居养老项目'高回报投资\n• '以房养老'保险骗局\n• '养老床位'预售投资\n• 防范：年化超过6%的养老项目基本是骗局\n\n3️⃣ 旅游骗局\n• 低价旅游团（'99元云南游'）——强制购物\n• 免费旅游（实际是卖房/卖保健品）\n\n4️⃣ 冒充诈骗\n• 冒充'民政局''医保局'电话诈骗\n• 冒充子女朋友借钱\n• 防范：任何要求转账的电话先和子女核实\n\n【防骗口诀】\n不贪小便宜，不信陌生人，不转账汇款，多和子女商量",
     "tags": "防骗,保健品,投资,安全"},
    {"city_id": None, "category": "出行攻略", "title": "使用美丽新乡村平台查找全国农村租房", "source": "美丽新乡村官网 myxiangcun.com",
     "content": "美丽新乡村（myxiangcun.com）是国内专业的农村宅基地和房屋出租信息平台，提供全国超过50,000套农村闲置房屋、农家院、宅基地出租信息。\n\n【平台特色】\n- 覆盖全国31个省市自治区的农村房源\n- 北京农村房源最多，其次是浙江、安徽、海南、云南等省市\n- 房源类型包括：农村整院、农家乐、康养农居、宅基地出租等\n- 年租金从几千元到几万元不等，适合候鸟老人预算\n\n【如何查找适合旅居的农村房源】\n\n1. 访问网站：https://myxiangcun.com/\n   或直接访问移动版：https://myxiangcun.com/m/anjialist.html\n\n2. 筛选省份：在顶部选择省份（如云南、海南、广西等候鸟热门省份）\n\n3. 进一步筛选：按租金价格、出租年限、面积大小筛选\n\n4. 联系房东：每个房源都有联系方式，直接致电或微信联系\n\n【候鸟旅居推荐搜索区域】\n- 云南：大理、丽江、西双版纳周边农村（月租500-1500元）\n- 海南：海口、琼海、万宁周边农村（月租800-2000元）\n- 广西：北海、巴马、阳朔周边农村（月租400-1000元）\n- 浙江：安吉、桐庐、丽水等美丽乡村（月租600-1200元）\n- 安徽：黟县、歙县、宣城等徽派古村（月租300-600元）\n- 贵州：兴义、凯里、安顺等避暑地（月租400-800元）\n\n【联系方式】\n客服电话：010-56247008（工作日09:30-17:30）\n微信公众号：meilixxc（随时查看最新房源）\n\n【注意事项】\n- 农村房源信息由房东自行发布，建议实地看房后再签约\n- 注意核实房源是否仍在出租，部分已租未下架\n- 通过本平台（候鸟旅居通）首页的[农村]标签可直接嵌入浏览美丽新乡村",
     "tags": "美丽新乡村,农村租房,平台,集合"},
    {"city_id": None, "category": "出行攻略", "title": "成都周边旅居全攻略", "source": "综合整理",
     "content": "成都连续多年蝉联中国最宜居城市，医疗交通配套全国顶级。\n\n【市区旅居】\n• 华西医院周边：医疗最方便，月租2500-3500元\n• 锦里/武侯祠周边：老成都文化浓厚\n• 温江/郫都：环境好，租金相对低\n\n【成都周边短途推荐】\n• 都江堰/青城山：避暑胜地，高铁30分钟，月租1000-2000元\n• 峨眉山：夏季凉爽，山上山下温差大\n• 邛崃/大邑：安仁古镇，刘氏庄园，月租800-1500元\n\n【成都生活贴士】\n• 美食之都，但川菜偏辣，初到者可选'微辣'或'白味'\n• 茶馆文化浓厚，适合社交\n• 成都市老年人优待政策好，景点/公交均有优惠\n• 夏季闷热，但比长江中下游城市好\n• 华西医院全国排名第二，看病最放心",
     "tags": "成都,四川,美食,医疗"},
]

def seed():
    db = SessionLocal()
    try:
        if db.query(City).count() > 0:
            print("数据库已有数据，跳过初始化")
            return
        for c in cities_data:
            city = City(**c)
            db.add(city)
        db.flush()
        # Deduplicate cities: keep the first occurrence, merge related records
        dupes = db.query(City.name, func.count(City.id)).group_by(City.name).having(func.count(City.id) > 1).all()
        for name, cnt in dupes:
            cities = db.query(City).filter(City.name == name).order_by(City.id).all()
            keep = cities[0]
            for dup in cities[1:]:
                db.query(House).filter(House.city_id == dup.id).update({"city_id": keep.id})
                db.query(Review).filter(Review.city_id == dup.id).update({"city_id": keep.id})
                db.query(Guide).filter(Guide.city_id == dup.id).update({"city_id": keep.id})
                db.delete(dup)
            print(f"  合并重复城市: {name} (保留ID={keep.id}, 删除{cnt-1}个重复)")
        db.flush()
        # Build name→id lookup for house/review assignment
        city_map = {c.name: c.id for c in db.query(City).all()}
        # Add houses (resolve _city_name for any entry that has it)
        for h in houses_data:
            if "_city_name" in h:
                h["city_id"] = city_map.get(h["_city_name"], h.get("city_id"))
            if "city_id" not in h:
                continue
            house = House(**{k:v for k,v in h.items() if not k.startswith("_")})
            db.add(house)
        db.flush()
        for r in reviews_data:
            if "_city_name" in r:
                r["city_id"] = city_map.get(r["_city_name"], r.get("city_id"))
            if "city_id" not in r:
                continue
            review = Review(**{k:v for k,v in r.items() if not k.startswith("_")})
            db.add(review)
        for g in guides_data:
            guide = Guide(**g)
            db.add(guide)
        db.commit()
        print(f"初始化完成：{city_map}")
        print(f"  {len(city_map)}个城市, {len(houses_data)}个房源, {len(reviews_data)}条评价, {len(guides_data)}篇攻略")
    finally:
        db.close()

if __name__ == "__main__":
    seed()
