import { User, Skill, Order, Review, Category, Banner, OrderStatus } from '@/types';

// Mock用户数据
export const mockUsers: User[] = [
  {
    id: '1',
    nickname: '张师傅',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix',
    phone: '138****1234',
    creditScore: 95,
    isVerified: true,
  },
  {
    id: '2',
    nickname: '李阿姨',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aneka',
    phone: '139****5678',
    creditScore: 88,
    isVerified: true,
  },
  {
    id: '3',
    nickname: '王老师',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Leo',
    phone: '137****9012',
    creditScore: 92,
    isVerified: true,
  },
  {
    id: '4',
    nickname: '小陈',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Chen',
    phone: '136****3456',
    creditScore: 85,
    isVerified: false,
  },
  {
    id: '5',
    nickname: '赵姐',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Zhao',
    phone: '135****7890',
    creditScore: 90,
    isVerified: true,
  },
];

// Mock分类数据
export const mockCategories: Category[] = [
  { id: '1', name: '家电维修', icon: 'Wrench', count: 45 },
  { id: '2', name: '手机教学', icon: 'Smartphone', count: 32 },
  { id: '3', name: '理发服务', icon: 'Scissors', count: 18 },
  { id: '4', name: '辅导作业', icon: 'BookOpen', count: 56 },
  { id: '5', name: '跑腿代劳', icon: 'Running', count: 28 },
  { id: '6', name: '手工技能', icon: 'Palette', count: 22 },
  { id: '7', name: '宠物照料', icon: 'Cat', count: 15 },
  { id: '8', name: '更多服务', icon: 'MoreHorizontal', count: 0 },
];

// Mock技能数据
export const mockSkills: Skill[] = [
  {
    id: '1',
    userId: '1',
    user: mockUsers[0],
    title: '家电维修专家',
    category: '家电维修',
    description: '擅长各类家电维修，包括空调、冰箱、洗衣机、电视等。20年维修经验，快速诊断问题，价格实惠。服务范围覆盖本小区及周边3公里。',
    price: 30,
    priceUnit: '次',
    rating: 4.9,
    serviceCount: 156,
    images: [
      'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=professional%20repairman%20fixing%20home%20appliances%20in%20modern%20apartment&image_size=landscape_4_3',
    ],
    distance: 0.5,
    isActive: true,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    userId: '2',
    user: mockUsers[1],
    title: '智能手机教学',
    category: '手机教学',
    description: '耐心教老年人使用智能手机，包括微信聊天、视频通话、网购、扫码支付等。一对一教学，上门服务，让爸妈轻松学会用手机。',
    price: 20,
    priceUnit: '小时',
    rating: 4.8,
    serviceCount: 89,
    images: [
      'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=friendly%20lady%20teaching%20elderly%20person%20how%20to%20use%20smartphone&image_size=landscape_4_3',
    ],
    distance: 0.8,
    isActive: true,
    createdAt: '2024-02-01',
  },
  {
    id: '3',
    userId: '3',
    user: mockUsers[2],
    title: '中小学作业辅导',
    category: '辅导作业',
    description: '重点中学退休教师，擅长小学、初中数学、语文、英语辅导。耐心细致，帮助孩子养成良好学习习惯，提升学习成绩。',
    price: 50,
    priceUnit: '小时',
    rating: 5.0,
    serviceCount: 234,
    images: [
      'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=experienced%20teacher%20tutoring%20student%20at%20home&image_size=landscape_4_3',
    ],
    distance: 1.2,
    isActive: true,
    createdAt: '2024-01-20',
  },
  {
    id: '4',
    userId: '4',
    user: mockUsers[3],
    title: '上门理发服务',
    category: '理发服务',
    description: '专业理发师，提供上门理发服务。擅长男士发型、老人理发、儿童理发。自带工具，干净卫生，价格实惠。',
    price: 15,
    priceUnit: '次',
    rating: 4.7,
    serviceCount: 67,
    images: [
      'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=hairdresser%20cutting%20hair%20at%20client%20home&image_size=landscape_4_3',
    ],
    distance: 0.3,
    isActive: true,
    createdAt: '2024-03-05',
  },
  {
    id: '5',
    userId: '5',
    user: mockUsers[4],
    title: '代跑腿服务',
    category: '跑腿代劳',
    description: '可帮忙买菜、取快递、送文件、接送孩子等。时间灵活，服务周到，小区内随时响应。',
    price: 10,
    priceUnit: '次',
    rating: 4.6,
    serviceCount: 45,
    images: [
      'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=friendly%20person%20helping%20with%20errands%20in%20residential%20community&image_size=landscape_4_3',
    ],
    distance: 0.6,
    isActive: true,
    createdAt: '2024-02-15',
  },
  {
    id: '6',
    userId: '1',
    user: mockUsers[0],
    title: '水电维修安装',
    category: '家电维修',
    description: '专业水电维修，包括换灯泡、安装开关、修理水管、疏通下水道等。快速响应，价格透明。',
    price: 25,
    priceUnit: '次',
    rating: 4.8,
    serviceCount: 112,
    images: [
      'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=plumber%20fixing%20water%20pipes%20in%20modern%20apartment&image_size=landscape_4_3',
    ],
    distance: 0.5,
    isActive: true,
    createdAt: '2024-01-10',
  },
];

// Mock订单数据
export const mockOrders: Order[] = [
  {
    id: '1',
    userId: '2',
    user: mockUsers[1],
    skillId: '1',
    skill: mockSkills[0],
    providerId: '1',
    provider: mockUsers[0],
    status: 'completed',
    address: '阳光小区3号楼502室',
    serviceTime: '2024-03-10 14:00',
    remark: '空调不制冷，请帮忙检查',
    amount: 30,
    createdAt: '2024-03-08',
    completedAt: '2024-03-10',
  },
  {
    id: '2',
    userId: '3',
    user: mockUsers[2],
    skillId: '2',
    skill: mockSkills[1],
    providerId: '2',
    provider: mockUsers[1],
    status: 'in_progress',
    address: '阳光小区5号楼101室',
    serviceTime: '2024-03-15 10:00',
    remark: '教我妈用微信视频通话',
    amount: 40,
    createdAt: '2024-03-12',
  },
  {
    id: '3',
    userId: '4',
    user: mockUsers[3],
    skillId: '3',
    skill: mockSkills[2],
    providerId: '3',
    provider: mockUsers[2],
    status: 'pending',
    address: '阳光小区2号楼303室',
    serviceTime: '2024-03-18 16:00',
    remark: '辅导孩子数学作业',
    amount: 50,
    createdAt: '2024-03-14',
  },
  {
    id: '4',
    userId: '1',
    user: mockUsers[0],
    skillId: '5',
    skill: mockSkills[4],
    providerId: '5',
    provider: mockUsers[4],
    status: 'accepted',
    address: '阳光小区1号楼201室',
    serviceTime: '2024-03-16 09:00',
    remark: '帮忙去菜市场买菜',
    amount: 10,
    createdAt: '2024-03-13',
  },
];

// Mock评价数据
export const mockReviews: Review[] = [
  {
    id: '1',
    orderId: '1',
    userId: '2',
    user: mockUsers[1],
    skillId: '1',
    rating: 5,
    content: '张师傅技术很好，空调很快就修好了，价格也很实惠，非常满意！',
    images: [],
    createdAt: '2024-03-10',
  },
  {
    id: '2',
    orderId: '2',
    userId: '3',
    user: mockUsers[2],
    skillId: '2',
    rating: 5,
    content: '李阿姨特别耐心，我妈现在会用微信视频了，太感谢了！',
    images: [],
    createdAt: '2024-03-12',
  },
  {
    id: '3',
    orderId: '3',
    userId: '4',
    user: mockUsers[3],
    skillId: '3',
    rating: 4,
    content: '王老师很专业，孩子数学进步了不少。',
    images: [],
    createdAt: '2024-03-18',
  },
];

// Mock轮播图数据
export const mockBanners: Banner[] = [
  {
    id: '1',
    title: '邻里互助，温暖社区',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=warm%20community%20neighbors%20helping%20each%20other%20in%20sunny%20residential%20area&image_size=landscape_16_9',
    type: 'activity',
  },
  {
    id: '2',
    title: '本周热门技能推荐',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=popular%20skills%20and%20services%20in%20modern%20community&image_size=landscape_16_9',
    type: 'skill',
    link: '/skills',
  },
  {
    id: '3',
    title: '新人注册送50积分',
    image: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=welcome%20bonus%20gift%20for%20new%20users%20in%20community%20app&image_size=landscape_16_9',
    type: 'announcement',
  },
];

// 当前用户（模拟登录状态）
export const currentUser: User = {
  id: '6',
  nickname: '我',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Me',
  creditScore: 80,
  isVerified: false,
};

// 订单状态映射
export const orderStatusMap: Record<OrderStatus, { label: string; color: string }> = {
  pending: { label: '待接单', color: 'status-pending' },
  accepted: { label: '已接单', color: 'status-accepted' },
  in_progress: { label: '进行中', color: 'status-in-progress' },
  completed: { label: '已完成', color: 'status-completed' },
  cancelled: { label: '已取消', color: 'status-cancelled' },
};